@startuml

left to right direction

package "DLT_Message_Analyzer" {
    package "DLT_Message_Analyzer_Source" {
        [dlt_message_analyzer_source]
    }
    
    package "DLT_Message_Analyzer_Github" {
        [dlt_message_analyzer_github]
    }
}

package "DLT_Message_Analyzer Dependencies" {
    package "DLT" {
        [qdlt]
    }

    package "Qt" {
        [qt5]
        [qt6]
    }

    package "QCustomPlot" {
        [qcustomplot]
    }

    package "DMA_Family" {
        [dma_plantuml]
        [dma_framework]
        [dma_common_deps]
    }

    package "Plantuml" {
        [plantuml]
    }

    package "Antlr" {
        [antlr4]
    }
    
    package "uuid" {
        [uuid_dev]
    }

    package "Pcre_parser" {
        [pcre_parser]
    }

    package "Variant_lite" {
        [variant_lite]
    }

    package "json"{
        [nlohmann/json]
    }

    package "Github_actions"{
        [actions/cache]
        [actions/checkout]
        [jurplel/install_qt_action]
        [stefanzweifel/git_auto_commit_action]
    }
    
    package "Build system"{
        [cmake]
    }
}

[dlt_message_analyzer_source] --> [dma_common_deps] : https://github.com/svlad-90/DMA_CommonDeps
[dlt_message_analyzer_source] --> [dma_framework] : https://github.com/svlad-90/DMA_Framework
[dlt_message_analyzer_source] --> [dma_plantuml] : https://github.com/svlad-90/DMA_Plantuml

[dlt_message_analyzer_source] --> [qt5] : https://github.com/qt/qt5
[dlt_message_analyzer_source] --> [qt6] : https://github.com/qt/qtbase
[dlt_message_analyzer_source] --> [qcustomplot] : https://gitlab.com/DerManu/QCustomPlot
[dlt_message_analyzer_source] --> [qdlt] : https://github.com/GENIVI/dlt-viewer/tree/master/qdlt
[dlt_message_analyzer_source] --> [plantuml] : https://github.com/plantuml/plantuml
[dlt_message_analyzer_source] --> [antlr4] : https://github.com/antlr/antlr4
[dlt_message_analyzer_source] --> [pcre_parser] : https://github.com/bkiers/pcre-parser
[dlt_message_analyzer_source] --> [variant_lite] : https://github.com/martinmoene/variant-lite
[dlt_message_analyzer_source] --> [cmake] : https://gitlab.kitware.com/cmake/cmake

[antlr4] --> [uuid_dev]

[dlt_message_analyzer_github] --> [actions/cache] : https://github.com/actions/cache
[dlt_message_analyzer_github] --> [actions/checkout] : https://github.com/actions/checkout
[dlt_message_analyzer_github] --> [jurplel/install_qt_action] : https://github.com/jurplel/install-qt-action
[dlt_message_analyzer_github] --> [stefanzweifel/git_auto_commit_action] : https://github.com/stefanzweifel/git-auto-commit-action

[dlt_message_analyzer_github] --> [nlohmann/json] : https://github.com/nlohmann/json

@enduml