
@startuml

skinparam backgroundColor #FEFEFE
skinparam wrapWidth 600
package "DLT" #DDDDDD
{

interface "QDLTPluginInterface"
{
}

class "QDltFile"
{
}

class "QDltMsg"
{
}

class "QDltPlugin"
{
}

interface "QDltPluginControlInterface"
{
}

class "QDltPluginManager"
{
}

interface "QDltPluginViewerInterface"
{
}

}

package "DMA_LogsWrapper" #DDDDDD
{

class "CDLTFileWrapper"
{
}

class "CDLTMsgDecoder"
{
}

class "CDLTMsgWrapper"
{
}

}

package "DMA_LogsWrapper_API" #DDDDDD
{

class "IDLTLogsWrapperCreator"
{
    + {abstract} virtual tFileWrapperPtr createDLTFileWrapper( QDltFile* pFile ) const = 0
    + {abstract} virtual tMsgDecoderPtr createMsgDecoder(const tPluginPtrList& decoderPlugins) const = 0
    + {abstract} virtual tMsgWrapperPtr createDLTMsgWrapper( QDltMsg& msg ) const = 0
}

}

package "DMA_Root" #DDDDDD
{

class "CDLTMessageAnalyzer"
{
}

class "DLTMessageAnalyzerPlugin"
{
}

}

'====================Inheritance section====================
QDLTPluginInterface <|-- DLTMessageAnalyzerPlugin : implements
QDltPluginControlInterface <|-- DLTMessageAnalyzerPlugin : implements
QDltPluginViewerInterface <|-- DLTMessageAnalyzerPlugin : implements

'====================Dependencies section====================
CDLTFileWrapper "1" o-- "1" QDltFile : uses
CDLTMsgDecoder "1" o-- "1" QDltMsg : uses
CDLTMsgWrapper "1" --> "1" QDltMsg : uses
IDLTLogsWrapperCreator "1" --> "*" QDltFile : uses
IDLTLogsWrapperCreator "1" --> "*" QDltMsg : uses
IDLTLogsWrapperCreator "1" --> "*" QDltPlugin : uses
CDLTMessageAnalyzer "1" o-- "many" QDltPlugin : uses
CDLTMessageAnalyzer "1" *-- "1" QDltPluginManager : contains

@enduml