
@startuml

skinparam backgroundColor #FEFEFE
skinparam wrapWidth 600
package "DLT" #DDDDDD
{

interface "QDLTPluginInterface"
{
}

class "QDltFile"
{
}

class "QDltMsg"
{
}

class "QDltPlugin"
{
}

interface "QDltPluginControlInterface"
{
}

class "QDltPluginManager"
{
}

interface "QDltPluginViewerInterface"
{
}

}

@enduml