
@startuml

skinparam backgroundColor #FEFEFE
skinparam wrapWidth 600
package "DMA_FiltersView" #DDDDDD
{

class "CFilterItemDelegate"
{
}

class "CFiltersModel"
{
}

}

package "DMA_FiltersView_API" #DDDDDD
{

class "IFiltersModel"
{
    + {abstract} virtual void addCompletionData( const tFoundMatches& foundMatches ) = 0
    + {abstract} virtual void filterRegexTokens( const QString& filter ) = 0
    + {abstract} virtual void resetCompletionData() = 0
    + {abstract} virtual void resetData() = 0
    + {abstract} virtual void setUsedRegex(const QString& regexStr) = 0
}

}

package "DMA_Settings_API" #DDDDDD
{

class "CSettingsManagerClient"
{
}

}

package "Qt" #DDDDDD
{

class "QStyledItemDelegate"
{
}

}

'====================Inheritance section====================
CSettingsManagerClient <|-- CFilterItemDelegate : extends
QStyledItemDelegate <|-- CFilterItemDelegate : extends
CSettingsManagerClient <|-- CFiltersModel : extends
IFiltersModel <|-- CFiltersModel : implements

'====================Dependencies section====================
CFilterItemDelegate "1" o-- "1" CFiltersModel : uses

@enduml