
@startuml

skinparam backgroundColor #FEFEFE
skinparam wrapWidth 600
package "DMA_PlantumlView" #DDDDDD
{

class "CImageViewer"
{
}

}

package "Qt" #DDDDDD
{

class "QWidget"
{
}

}

'====================Inheritance section====================
QWidget <|-- CImageViewer : extends

@enduml