
@startuml

skinparam backgroundColor #FEFEFE
skinparam wrapWidth 600
package "DMA_Framework_Component" #DDDDDD
{

class "DMA::IComponent"
{
}

}

package "DMA_RegexHistory_API" #DDDDDD
{

class "CRegexHistoryComponent"
{
}

class "CRegexHistoryLineEdit"
{
}

class "IRegexHistoryProvider"
{
}

}

package "Qt" #DDDDDD
{

class "QLineEdit"
{
}

class "QObject"
{
}

}

'====================Inheritance section====================
DMA::IComponent <|-- CRegexHistoryComponent : implements
QLineEdit <|-- CRegexHistoryLineEdit : extends
QObject <|-- IRegexHistoryProvider : extends

'====================Dependencies section====================
CRegexHistoryComponent "1" --> "1" CRegexHistoryLineEdit : passes
CRegexHistoryLineEdit "1" o-- "1" IRegexHistoryProvider : uses

@enduml