
@startuml

skinparam backgroundColor #FEFEFE
skinparam wrapWidth 600
package "DMA_PlantumlView" #DDDDDD
{

class "CImageViewer"
{
}

}

package "DMA_PlantumlView_API" #DDDDDD
{

class "CUMLView"
{
}

}

package "Qt" #DDDDDD
{

class "QImage"
{
}

class "QWidget"
{
}

}

'====================Inheritance section====================
QWidget <|-- CImageViewer : extends

'====================Dependencies section====================
CImageViewer "1" *-- "1" QImage : contains
CUMLView "1" *-- "1" CImageViewer : contains

@enduml