
@startuml

skinparam backgroundColor #FEFEFE
skinparam wrapWidth 600
package "DMA_Framework_Component" #DDDDDD
{

class "DMA::IComponent"
{
}

}

package "DMA_PlantumlView" #DDDDDD
{

class "CImageViewer"
{
}

}

package "DMA_PlantumlView_API" #DDDDDD
{

class "CUMLView"
{
}

class "CUMLViewComponent"
{
}

}

package "DMA_Root" #DDDDDD
{

class "CDLTMessageAnalyzer"
{
}

class "DLTMessageAnalyzerPlugin"
{
}

class "Ui::Form"
{
}

}

package "DMA_Settings_API" #DDDDDD
{

class "CSettingsManagerClient"
{
}

}

package "Qt" #DDDDDD
{

class "QProcess"
{
}

class "QWidget"
{
}

}

'====================Inheritance section====================
CSettingsManagerClient <|-- CUMLView : extends
QWidget <|-- CUMLView : extends
CSettingsManagerClient <|-- CUMLViewComponent : extends
DMA::IComponent <|-- CUMLViewComponent : implements

'====================Dependencies section====================
CUMLView "1" *-- "1" CImageViewer : contains
CUMLView "1" *-- "2" QProcess : contains
CUMLViewComponent "1" o-- "1" CUMLView : uses
CDLTMessageAnalyzer "1" o-- "1" CUMLView : uses
DLTMessageAnalyzerPlugin "1" *-- "1" CUMLViewComponent : contains
Ui::Form "1" *-- "1" CUMLView : contains

@enduml