
@startuml

skinparam backgroundColor #FEFEFE
skinparam wrapWidth 600
package "DMA_Common" #DDDDDD
{

class "CTableMemoryJumper"
{
}

}

package "DMA_CoverageNote_API" #DDDDDD
{

class "ICoverageNoteProvider"
{
}

}

package "DMA_Framework_Component" #DDDDDD
{

class "DMA::IComponent"
{
}

}

package "DMA_LogsWrapper_API" #DDDDDD
{

class "IFileWrapper"
{
    + {abstract} virtual QString getCacheStatusAsString() const = 0
    + {abstract} virtual QString getFileName(int num = 0) = 0
    + {abstract} virtual bool cacheMsgByIndex( const tMsgId& msgId ) = 0
    + {abstract} virtual bool cacheMsgByIndexes( const QSet<tMsgId> msgIdSet ) = 0
    + {abstract} virtual bool cacheMsgByRange( const tIntRange& msgRange ) = 0
    + {abstract} virtual bool cacheMsgWrapper( const int& msgId, const tMsgWrapperPtr& pMsgWrapper ) = 0
    + {abstract} virtual bool getSubFilesHandlingStatus() const = 0
    + {abstract} virtual bool isFiltered() const = 0
    + {abstract} virtual int getMsgIdFromIndexInMainTable(int msgIdxInMainTable) const = 0
    + {abstract} virtual int getNumberOfFiles() const = 0
    + {abstract} virtual int size() const = 0
    + {abstract} virtual int sizeNonFiltered() const = 0
    + signal void currentSizeMbChanged(tCacheSizeMB MBytes)
    + signal void fullChanged(bool isFull)
    + signal void isEnabledChanged(bool isEnabled)
    + signal void loadChanged(unsigned int percents)
    + signal void maxSizeMbChanged(tCacheSizeMB MBytes)
    + {abstract} virtual tIntRangeProperty normalizeSearchRange( const tIntRangeProperty& inputRange) = 0
    + {abstract} virtual tMsgWrapperPtr getMsg(const tMsgId& msgId) = 0
    + {abstract} virtual virtual tIntRangeList getSubFilesSizeRanges() const = 0
    + {abstract} virtual void copyFileNameToClipboard( const int& msgId ) const = 0
    + {abstract} virtual void copyFileNamesToClipboard( const tIntRange& msgsRange ) const = 0
    + {abstract} virtual void resetCache() = 0
    + {abstract} virtual void setEnableCache(bool isEnabled) = 0
    + {abstract} virtual void setMaxCacheSize(const tCacheSizeB& cacheSize ) = 0
    + {abstract} virtual void setMessageDecoder( IMsgDecoder* pMessageDecoder ) = 0
    + {abstract} virtual void setSubFilesHandlingStatus(const bool& val) = 0
}

}

package "DMA_PlotView_API" #DDDDDD
{

class "CPlotViewComponent"
{
}

}

package "DMA_Plugin" #DDDDDD
{

class "DLTMessageAnalyzerPlugin"
{
}

}

package "DMA_Plugin_API" #DDDDDD
{

class "CDLTMessageAnalyzer"
{
}

class "Ui::Form"
{
}

}

package "DMA_SearchView" #DDDDDD
{

class "CSearchResultHighlightingDelegate"
{
}

class "CSearchResultModel"
{
}

}

package "DMA_SearchView_API" #DDDDDD
{

class "CSearchResultView"
{
}

class "CSearchViewComponent"
{
}

class "ISearchResultModel"
{
    + {abstract} virtual int getFileIdx( const QModelIndex& idx ) const = 0
    + {abstract} virtual std::pair<bool__tIntRange> addNextMessageIdxVec(const tFoundMatchesPack& foundMatchesPack) = 0
    + {abstract} virtual std::pair<int__QString > getUMLDiagramContent() const = 0
    + {abstract} virtual tPlotContent createPlotContent() const = 0
    + {abstract} virtual void resetData() = 0
    + {abstract} virtual void setFile(const tFileWrapperPtr& pFile) = 0
    + {abstract} virtual void updateView(const int& fromRow = 0) = 0
}

}

package "DMA_Settings_API" #DDDDDD
{

class "CSettingsManagerClient"
{
}

}

package "Qt" #DDDDDD
{

class "QObject"
{
}

class "QTabWidget"
{
}

class "QTableView"
{
}

}

'====================Inheritance section====================
ISearchResultModel <|-- CSearchResultModel : implements
QTableView <|-- CSearchResultView : extends
CSettingsManagerClient <|-- CSearchViewComponent : extends
DMA::IComponent <|-- CSearchViewComponent : implements
QObject <|-- CSearchViewComponent : extends

'====================Dependencies section====================
CPlotViewComponent "1" o-- "1" ISearchResultModel : uses
DLTMessageAnalyzerPlugin "1" *-- "1" CSearchViewComponent : contains
CDLTMessageAnalyzer "1" o-- "1" CSearchResultView : uses
CDLTMessageAnalyzer "1" o-- "1" ISearchResultModel : gets and uses
Ui::Form "1" *-- "1" CSearchResultView : contains
CSearchResultHighlightingDelegate "1" *-- "1" ISearchResultModel : uses
CSearchResultView "1" o-- "1" CSearchResultModel : uses
CSearchResultView "1" o-- "1" ICoverageNoteProvider : uses
CSearchResultView "1" o-- "1" IFileWrapper : uses
CSearchResultView "1" o-- "1" QTabWidget : uses main tab widget
CSearchResultView "1" o-- "1" QTableView : uses dlt-viewer main table view
CSearchViewComponent "1" --> "1" CSearchResultModel : using to create ISearchResultModel
CSearchViewComponent "1" o-- "1" CSearchResultView : uses
CSearchViewComponent "1" *-- "1" CTableMemoryJumper : contains
CSearchViewComponent "1" o-- "1" ICoverageNoteProvider : uses
CSearchViewComponent "1" *-- "1" ISearchResultModel : contains
CSearchViewComponent "1" o-- "1" QTabWidget : uses

@enduml