
@startuml

skinparam backgroundColor #FEFEFE
skinparam wrapWidth 600
package "DMA_Analyzer_API" #DDDDDD
{

abstract class "IDLTMessageAnalyzerControllerConsumer"
{
    + {abstract} virtual slot void progressNotification( const tProgressNotificationData& progressNotificationData ) = 0
    + tRequestId requestAnalyze( const tRequestParameters& requestParameters )
}

}

package "DMA_Plugin_API" #DDDDDD
{

class "CDLTMessageAnalyzer"
{
}

class "Form"
{
}

class "Ui::Form"
{
}

}

package "DMA_Settings_API" #DDDDDD
{

class "CSettingsManagerClient"
{
}

}

package "Qt" #DDDDDD
{

class "QWidget"
{
}

}

'====================Inheritance section====================
CSettingsManagerClient <|-- CDLTMessageAnalyzer : extends
IDLTMessageAnalyzerControllerConsumer <|-- CDLTMessageAnalyzer : implements
CSettingsManagerClient <|-- Form : extends
QWidget <|-- Form : extends

'====================Dependencies section====================
Form "1" *-- "1" Ui::Form : contains

@enduml