
@startuml

skinparam backgroundColor #FEFEFE
skinparam wrapWidth 600
package "DMA_Framework_Component" #DDDDDD
{

class "DMA::IComponent"
{
}

}

package "DMA_PatternsView" #DDDDDD
{

class "CPatternsModel"
{
}

}

package "DMA_PatternsView_API" #DDDDDD
{

class "CPatternsView"
{
}

class "CPatternsViewComponent"
{
}

class "CTreeRepresentationDelegate"
{
}

class "IPatternsModel"
{
    + {abstract} virtual QModelIndex addData(const QString& alias, const QString& regex, Qt::CheckState isCombine, Qt::CheckState isDefault) = 0
    + {abstract} virtual QModelIndex addData(const QString& alias, const QString& regex, Qt::CheckState isDefault = Qt::Unchecked) = 0
    + {abstract} virtual QModelIndex editData(const QModelIndex& idx, const QString& alias, const QString& regex, Qt::CheckState isDefault, Qt::CheckState isCombine) = 0
    + {abstract} virtual QString getAliasEditName( const QModelIndex& idx ) = 0
    + {abstract} virtual removeData(const QModelIndex& idx) = 0
    + {abstract} virtual signal void patternsRefreshed() = 0
    + {abstract} virtual tSearchResult search( const QString& alias ) = 0
    + {abstract} virtual void filterPatterns( const QString& filter ) = 0
    + {abstract} virtual void refreshRegexPatterns() = 0
    + {abstract} virtual void resetData() = 0
    + {abstract} virtual void updatePatternsInPersistency() = 0
    + {abstract} virtual void updateView() = 0
}

}

package "DMA_Plugin" #DDDDDD
{

class "DLTMessageAnalyzerPlugin"
{
}

}

package "DMA_Plugin_API" #DDDDDD
{

class "CDLTMessageAnalyzer"
{
}

class "Ui::Form"
{
}

}

package "DMA_RegexHistory" #DDDDDD
{

class "CRegexHistoryProvider"
{
}

}

package "DMA_RegexHistory_API" #DDDDDD
{

class "CRegexHistoryComponent"
{
}

}

package "DMA_Settings_API" #DDDDDD
{

class "CSettingsManagerClient"
{
}

}

package "Qt" #DDDDDD
{

abstract class "QAbstractItemModel"
{
}

class "QLineEdit"
{
}

class "QStyledItemDelegate"
{
}

class "QTreeView"
{
}

}

'====================Inheritance section====================
IPatternsModel <|-- CPatternsModel : implements
CSettingsManagerClient <|-- CPatternsView : extends
QTreeView <|-- CPatternsView : extends
CSettingsManagerClient <|-- CPatternsViewComponent : extends
DMA::IComponent <|-- CPatternsViewComponent : implements
QStyledItemDelegate <|-- CTreeRepresentationDelegate : extends
QAbstractItemModel <|-- IPatternsModel : implements

'====================Dependencies section====================
CPatternsView "1" o-- "1" CPatternsModel : uses
CPatternsView "1" *-- "1" CTreeRepresentationDelegate : contains
CPatternsView "1" o-- "1" QLineEdit : patterns search input
CPatternsViewComponent "1" --> "1" CPatternsModel : using to create IPatternsModel
CPatternsViewComponent "1" o-- "1" CPatternsView : uses
CPatternsViewComponent "1" *-- "1" IPatternsModel : contains
DLTMessageAnalyzerPlugin "1" *-- "1" CPatternsViewComponent : contains
CDLTMessageAnalyzer "1" o-- "1" CPatternsView : uses
CDLTMessageAnalyzer "1" o-- "1" IPatternsModel : uses
Ui::Form "1" *-- "1" CPatternsView : contains
CRegexHistoryProvider "1" o-- "1" CPatternsView : uses
CRegexHistoryComponent "1" o-- "1" CPatternsView : uses

@enduml