
@startuml

skinparam wrapWidth 600
package "DMA_SearchView" #DDDDDD
{

class "CSearchResultHighlightingDelegate"
{
}

class "CSearchResultModel"
{
}

class "CSearchResultView"
{
}

}

'====================Inheritance section====================
QStyledItemDelegate <|-- CSearchResultHighlightingDelegate : extends
QAbstractTableModel <|-- CSearchResultModel : implements
QTableView <|-- CSearchResultView : extends

'====================Dependencies section====================
CSearchResultHighlightingDelegate "1" *-- "1" CSearchResultModel : uses
CSearchResultView "1" o-- "1" CSearchResultModel : uses

@enduml