
@startuml

skinparam wrapWidth 600
package "DMA_Analyzer" #DDDDDD
{

class "CContinuousAnalyzer"
{
}

class "CDLTRegexAnalyzerWorker"
{
}

class "CMTAnalyzer"
{
}

class "CSubConsumer"
{
}

abstract class "IDLTMessageAnalyzerController"
{
    + {abstract} virtual int getMaximumNumberOfThreads() const = 0
    + {abstract} virtual tRequestId requestAnalyze( const std::weak_ptr<IDLTMessageAnalyzerControllerConsumer>& pClient, const tDLTFileWrapperPtr& pFile, const int& fromMessage, const int& numberOfMessages, const QRegularExpression& regex, const int& numberOfThreads, const tRegexScriptingMetadata& regexScriptingMetadata, bool isContinuous) = 0
    + {abstract} virtual void cancelRequest( const std::weak_ptr<IDLTMessageAnalyzerControllerConsumer>& pClient, const tRequestId& requestId ) = 0
}

abstract class "IDLTMessageAnalyzerControllerConsumer"
{
    + tRequestId requestAnalyze( const tDLTFileWrapperPtr& pFile, const int& fromMessage, const int& numberOfMessages, const QRegularExpression& regex, const int& numberOfThreads, bool isContinuous )
    + {abstract} virtual void progressNotification( const tRequestId& requestId, const eRequestState& requestState, const int8_t& progress, const tFoundMatchesPack& processedMatches) = 0
}

class "std::enable_shared_from_this<IDLTMessageAnalyzerControllerConsumer>" as std::enable_shared_from_this_IDLTMessageAnalyzerControllerConsumer_
{
}

}

package "DMA_Root" #DDDDDD
{

class "CDLTMessageAnalyzer"
{
}

class "DLTMessageAnalyzerPlugin"
{
}

}

package "Qt" #DDDDDD
{

class "QObject"
{
}

class "QThread"
{
}

}

'====================Inheritance section====================
IDLTMessageAnalyzerController <|-- CContinuousAnalyzer : implements
QObject <|-- CDLTRegexAnalyzerWorker : extends
IDLTMessageAnalyzerController <|-- CMTAnalyzer : implements
IDLTMessageAnalyzerControllerConsumer <|-- CSubConsumer : implements
QObject <|-- IDLTMessageAnalyzerController : extends
QObject <|-- IDLTMessageAnalyzerControllerConsumer : extends
std::enable_shared_from_this_IDLTMessageAnalyzerControllerConsumer_ <|-- IDLTMessageAnalyzerControllerConsumer : extends
IDLTMessageAnalyzerControllerConsumer <|-- CDLTMessageAnalyzer : implements

'====================Dependencies section====================
CContinuousAnalyzer "1" o-- "1" IDLTMessageAnalyzerController : uses
CContinuousAnalyzer "1" *-- "1" IDLTMessageAnalyzerControllerConsumer : contains
CMTAnalyzer "1" *-- "*" CDLTRegexAnalyzerWorker : contains
CMTAnalyzer "1" *-- "*" QThread : contains
IDLTMessageAnalyzerControllerConsumer "1" o-- "1" IDLTMessageAnalyzerController : uses
DLTMessageAnalyzerPlugin "1" *-- "1" IDLTMessageAnalyzerController : contains

@enduml