
@startuml

skinparam backgroundColor #FEFEFE
skinparam wrapWidth 600
package "DMA_Framework_Component" #DDDDDD
{

class "DMA::IComponent"
{
}

}

package "DMA_PatternsView_API" #DDDDDD
{

class "CPatternsView"
{
}

class "CPatternsViewComponent"
{
}

class "CTreeRepresentationDelegate"
{
}

class "IPatternsModel"
{
    + {abstract} virtual QModelIndex addData(const QString& alias, const QString& regex, Qt::CheckState isCombine, Qt::CheckState isDefault) = 0
    + {abstract} virtual QModelIndex addData(const QString& alias, const QString& regex, Qt::CheckState isDefault = Qt::Unchecked) = 0
    + {abstract} virtual QModelIndex editData(const QModelIndex& idx, const QString& alias, const QString& regex, Qt::CheckState isDefault, Qt::CheckState isCombine) = 0
    + {abstract} virtual QString getAliasEditName( const QModelIndex& idx ) = 0
    + {abstract} virtual removeData(const QModelIndex& idx) = 0
    + {abstract} virtual signal void patternsRefreshed() = 0
    + {abstract} virtual tSearchResult search( const QString& alias ) = 0
    + {abstract} virtual void filterPatterns( const QString& filter ) = 0
    + {abstract} virtual void refreshRegexPatterns() = 0
    + {abstract} virtual void resetData() = 0
    + {abstract} virtual void updatePatternsInPersistency() = 0
    + {abstract} virtual void updateView() = 0
}

}

package "DMA_Settings_API" #DDDDDD
{

class "CSettingsManagerClient"
{
}

}

package "Qt" #DDDDDD
{

abstract class "QAbstractItemModel"
{
}

class "QStyledItemDelegate"
{
}

class "QTreeView"
{
}

}

'====================Inheritance section====================
CSettingsManagerClient <|-- CPatternsView : extends
QTreeView <|-- CPatternsView : extends
CSettingsManagerClient <|-- CPatternsViewComponent : extends
DMA::IComponent <|-- CPatternsViewComponent : implements
QStyledItemDelegate <|-- CTreeRepresentationDelegate : extends
QAbstractItemModel <|-- IPatternsModel : implements

'====================Dependencies section====================
CPatternsView "1" *-- "1" CTreeRepresentationDelegate : contains
CPatternsViewComponent "1" o-- "1" CPatternsView : uses
CPatternsViewComponent "1" *-- "1" IPatternsModel : contains

@enduml