
@startuml

skinparam backgroundColor #FEFEFE
skinparam wrapWidth 600
package "DMA_Analyzer_API" #DDDDDD
{

abstract class "IDLTMessageAnalyzerController"
{
    + {abstract} virtual int getMaximumNumberOfThreads() const = 0
    + signal void progressNotification( const tProgressNotificationData& progressNotificationData )
    + {abstract} virtual tRequestId requestAnalyze( const std::weak_ptr<IDLTMessageAnalyzerControllerConsumer>& pClient, const tRequestParameters& requestParameters ) = 0
    + {abstract} virtual void cancelRequest( const std::weak_ptr<IDLTMessageAnalyzerControllerConsumer>& pClient, const tRequestId& requestId ) = 0
}

}

package "DMA_PatternsView_API" #DDDDDD
{

class "CPatternsView"
{
}

}

package "DMA_RegexHistory" #DDDDDD
{

class "CExtendedCompleter"
{
}

class "CRegexHistoryProvider"
{
}

}

package "DMA_RegexHistory_API" #DDDDDD
{

class "CRegexHistoryComponent"
{
}

class "CRegexHistoryTextEdit"
{
}

class "IRegexHistoryProvider"
{
}

}

package "DMA_Settings_API" #DDDDDD
{

class "CSettingsManagerClient"
{
}

class "ISettingsManager"
{
}

}

package "Qt" #DDDDDD
{

class "QCompleter"
{
}

class "QListView"
{
}

}

'====================Inheritance section====================
QCompleter <|-- CExtendedCompleter : extends
CSettingsManagerClient <|-- CRegexHistoryProvider : extends
IRegexHistoryProvider <|-- CRegexHistoryProvider : implements

'====================Dependencies section====================
CRegexHistoryProvider "1" *-- "1" CExtendedCompleter : creates
CRegexHistoryProvider "1" o-- "1" CPatternsView : uses
CRegexHistoryProvider "1" o-- "1" CRegexHistoryTextEdit : uses
CRegexHistoryProvider "1" o-- "1" IDLTMessageAnalyzerController : uses
CRegexHistoryProvider "1" o-- "1" ISettingsManager : uses
CRegexHistoryProvider "1" *-- "1" QListView : creates
CRegexHistoryComponent "1" *-- "1" CRegexHistoryProvider : creates

@enduml