
@startuml

skinparam backgroundColor #FEFEFE
skinparam wrapWidth 600
package "DMA_Analyzer" #DDDDDD
{

class "CContinuousAnalyzer"
{
}

class "CMTAnalyzer"
{
}

class "CSubConsumer"
{
}

}

package "DMA_Analyzer_API" #DDDDDD
{

class "CAnalyzerComponent"
{
}

abstract class "IDLTMessageAnalyzerController"
{
    + {abstract} virtual int getMaximumNumberOfThreads() const = 0
    + signal void progressNotification( const tProgressNotificationData& progressNotificationData )
    + {abstract} virtual tRequestId requestAnalyze( const std::weak_ptr<IDLTMessageAnalyzerControllerConsumer>& pClient, const tRequestParameters& requestParameters ) = 0
    + {abstract} virtual void cancelRequest( const std::weak_ptr<IDLTMessageAnalyzerControllerConsumer>& pClient, const tRequestId& requestId ) = 0
}

abstract class "IDLTMessageAnalyzerControllerConsumer"
{
    + {abstract} virtual slot void progressNotification( const tProgressNotificationData& progressNotificationData ) = 0
    + tRequestId requestAnalyze( const tRequestParameters& requestParameters )
}

class "std::enable_shared_from_this<IDLTMessageAnalyzerControllerConsumer>" as std::enable_shared_from_this_IDLTMessageAnalyzerControllerConsumer_
{
}

}

package "DMA_Framework_Component" #DDDDDD
{

class "DMA::IComponent"
{
}

}

package "DMA_LogsWrapper_API" #DDDDDD
{

class "IFileWrapper"
{
    + {abstract} virtual QString getCacheStatusAsString() const = 0
    + {abstract} virtual QString getFileName(int num = 0) = 0
    + {abstract} virtual bool cacheMsgByIndex( const tMsgId& msgId ) = 0
    + {abstract} virtual bool cacheMsgByIndexes( const QSet<tMsgId> msgIdSet ) = 0
    + {abstract} virtual bool cacheMsgByRange( const tIntRange& msgRange ) = 0
    + {abstract} virtual bool cacheMsgWrapper( const int& msgId, const tMsgWrapperPtr& pMsgWrapper ) = 0
    + {abstract} virtual bool getSubFilesHandlingStatus() const = 0
    + {abstract} virtual bool isFiltered() const = 0
    + {abstract} virtual int getMsgIdFromIndexInMainTable(int msgIdxInMainTable) const = 0
    + {abstract} virtual int getNumberOfFiles() const = 0
    + {abstract} virtual int size() const = 0
    + {abstract} virtual int sizeNonFiltered() const = 0
    + signal void currentSizeMbChanged(tCacheSizeMB MBytes)
    + signal void fullChanged(bool isFull)
    + signal void isEnabledChanged(bool isEnabled)
    + signal void loadChanged(unsigned int percents)
    + signal void maxSizeMbChanged(tCacheSizeMB MBytes)
    + {abstract} virtual tIntRangeProperty normalizeSearchRange( const tIntRangeProperty& inputRange) = 0
    + {abstract} virtual tMsgWrapperPtr getMsg(const tMsgId& msgId) = 0
    + {abstract} virtual virtual tIntRangeList getSubFilesSizeRanges() const = 0
    + {abstract} virtual void copyFileNameToClipboard( const int& msgId ) const = 0
    + {abstract} virtual void copyFileNamesToClipboard( const tIntRange& msgsRange ) const = 0
    + {abstract} virtual void resetCache() = 0
    + {abstract} virtual void setEnableCache(bool isEnabled) = 0
    + {abstract} virtual void setMaxCacheSize(const tCacheSizeB& cacheSize ) = 0
    + {abstract} virtual void setMessageDecoder( IMsgDecoder* pMessageDecoder ) = 0
    + {abstract} virtual void setSubFilesHandlingStatus(const bool& val) = 0
}

}

package "DMA_Plugin" #DDDDDD
{

class "DLTMessageAnalyzerPlugin"
{
}

}

package "DMA_Plugin_API" #DDDDDD
{

class "CDLTMessageAnalyzer"
{
}

}

package "DMA_RegexHistory" #DDDDDD
{

class "CRegexHistoryProvider"
{
}

}

package "DMA_RegexHistory_API" #DDDDDD
{

class "CRegexHistoryComponent"
{
}

}

package "DMA_Settings_API" #DDDDDD
{

class "CSettingsManagerClient"
{
}

}

package "Qt" #DDDDDD
{

class "QObject"
{
}

}

'====================Inheritance section====================
IDLTMessageAnalyzerController <|-- CContinuousAnalyzer : implements
IDLTMessageAnalyzerController <|-- CMTAnalyzer : implements
IDLTMessageAnalyzerControllerConsumer <|-- CSubConsumer : implements
CSettingsManagerClient <|-- CAnalyzerComponent : extends
DMA::IComponent <|-- CAnalyzerComponent : implements
QObject <|-- IDLTMessageAnalyzerController : extends
QObject <|-- IDLTMessageAnalyzerControllerConsumer : extends
std::enable_shared_from_this_IDLTMessageAnalyzerControllerConsumer_ <|-- IDLTMessageAnalyzerControllerConsumer : extends
IDLTMessageAnalyzerControllerConsumer <|-- CDLTMessageAnalyzer : implements

'====================Dependencies section====================
CContinuousAnalyzer "1" o-- "1" IDLTMessageAnalyzerController : uses
CContinuousAnalyzer "1" *-- "1" IDLTMessageAnalyzerControllerConsumer : contains
CAnalyzerComponent "1" *-- "1" CContinuousAnalyzer : contains
CAnalyzerComponent "1" --> "1" CMTAnalyzer : creates and feeds into CContinuousAnalyzer
IDLTMessageAnalyzerController "1" --> "1" IFileWrapper : uses
IDLTMessageAnalyzerControllerConsumer "1" o-- "1" IDLTMessageAnalyzerController : uses
IDLTMessageAnalyzerControllerConsumer "1" --> "1" IFileWrapper : uses
DLTMessageAnalyzerPlugin "1" *-- "1" CAnalyzerComponent : contains
CDLTMessageAnalyzer "1" --> "1" IDLTMessageAnalyzerController : gets and feeds to IDLTMessageAnalyzerControllerConsumer
CRegexHistoryProvider "1" o-- "1" IDLTMessageAnalyzerController : uses
CRegexHistoryComponent "1" --> "1" IDLTMessageAnalyzerController : passes

@enduml