
@startuml

skinparam backgroundColor #FEFEFE
skinparam wrapWidth 600
package "DMA_FiltersView" #DDDDDD
{

class "CFilterItemDelegate"
{
}

class "CFiltersModel"
{
}

}

package "DMA_FiltersView_API" #DDDDDD
{

class "CFiltersView"
{
}

class "CFiltersViewComponent"
{
}

class "IFiltersModel"
{
    + {abstract} virtual void addCompletionData( const tFoundMatches& foundMatches ) = 0
    + {abstract} virtual void filterRegexTokens( const QString& filter ) = 0
    + {abstract} virtual void resetCompletionData() = 0
    + {abstract} virtual void resetData() = 0
    + {abstract} virtual void setUsedRegex(const QString& regexStr) = 0
}

}

package "DMA_Framework_Component" #DDDDDD
{

class "DMA::IComponent"
{
}

}

package "DMA_Plugin" #DDDDDD
{

class "DLTMessageAnalyzerPlugin"
{
}

}

package "DMA_Plugin_API" #DDDDDD
{

class "CDLTMessageAnalyzer"
{
}

class "Ui::Form"
{
}

}

package "DMA_RegexHistory_API" #DDDDDD
{

class "CRegexHistoryTextEdit"
{
}

}

package "DMA_Settings_API" #DDDDDD
{

class "CSettingsManagerClient"
{
}

}

package "Qt" #DDDDDD
{

abstract class "QAbstractItemModel"
{
}

class "QTreeView"
{
}

}

'====================Inheritance section====================
IFiltersModel <|-- CFiltersModel : implements
CSettingsManagerClient <|-- CFiltersView : extends
QTreeView <|-- CFiltersView : implements
CSettingsManagerClient <|-- CFiltersViewComponent : extends
DMA::IComponent <|-- CFiltersViewComponent : implements
QAbstractItemModel <|-- IFiltersModel : implements

'====================Dependencies section====================
CFiltersView "1" *-- "1" CFilterItemDelegate : contains
CFiltersView "1" o-- "1" CFiltersModel : uses
CFiltersView "1" o-- "1" CRegexHistoryTextEdit : regex input field
CFiltersViewComponent "1" --> "1" CFiltersModel : using to create IFiltersModel
CFiltersViewComponent "1" o-- "1" CFiltersView : uses
CFiltersViewComponent "1" *-- "1" IFiltersModel : contains
DLTMessageAnalyzerPlugin "1" *-- "1" CFiltersViewComponent : contains
CDLTMessageAnalyzer "1" o-- "1" CFiltersView : uses
CDLTMessageAnalyzer "1" o-- "1" IFiltersModel : uses
Ui::Form "1" *-- "1" CFiltersView : contains

@enduml