
@startuml

skinparam backgroundColor #FEFEFE
skinparam wrapWidth 600
package "DMA_Framework_Component" #DDDDDD
{

class "DMA::IComponent"
{
}

}

package "DMA_GroupedView" #DDDDDD
{

class "CGroupedViewModel"
{
}

}

package "DMA_GroupedView_API" #DDDDDD
{

class "CGroupedView"
{
}

class "CGroupedViewComponent"
{
}

class "IGroupedViewModel"
{
    + {abstract} virtual int rowCount(const QModelIndex &parent = QModelIndex()) const = 0
    + {abstract} virtual std::pair<bool__QString> exportToHTML(QString& resultHTML) = 0
    + {abstract} virtual void addMatches( const tFoundMatches& matches, bool update ) = 0
    + {abstract} virtual void resetData() = 0
    + {abstract} virtual void setUsedRegex(const QString& regex) = 0
}

}

package "DMA_Root" #DDDDDD
{

class "CDLTMessageAnalyzer"
{
}

class "DLTMessageAnalyzerPlugin"
{
}

class "Ui::Form"
{
}

}

package "DMA_Settings_API" #DDDDDD
{

class "CSettingsManagerClient"
{
}

}

package "Qt" #DDDDDD
{

class "QTreeView"
{
}

}

'====================Inheritance section====================
IGroupedViewModel <|-- CGroupedViewModel : implements
CSettingsManagerClient <|-- CGroupedView : extends
QTreeView <|-- CGroupedView : extends
CSettingsManagerClient <|-- CGroupedViewComponent : extends
DMA::IComponent <|-- CGroupedViewComponent : implements

'====================Dependencies section====================
CGroupedViewComponent "1" o-- "1" CGroupedView : uses
CGroupedViewComponent "1" --> "1" CGroupedViewModel : using to create IGroupedViewModel
CGroupedViewComponent "1" *-- "1" IGroupedViewModel : contains
CDLTMessageAnalyzer "1" *-- "1" IGroupedViewModel : uses
DLTMessageAnalyzerPlugin "1" *-- "1" CGroupedViewComponent : contains
Ui::Form "1" *-- "1" CGroupedView : contains

@enduml