
@startuml

skinparam backgroundColor #FEFEFE
skinparam wrapWidth 600
package "DMA_Analyzer_API" #DDDDDD
{

abstract class "IDLTMessageAnalyzerController"
{
    + {abstract} virtual int getMaximumNumberOfThreads() const = 0
    + signal void progressNotification( const tProgressNotificationData& progressNotificationData )
    + {abstract} virtual tRequestId requestAnalyze( const std::weak_ptr<IDLTMessageAnalyzerControllerConsumer>& pClient, const tRequestParameters& requestParameters ) = 0
    + {abstract} virtual void cancelRequest( const std::weak_ptr<IDLTMessageAnalyzerControllerConsumer>& pClient, const tRequestId& requestId ) = 0
}

abstract class "IDLTMessageAnalyzerControllerConsumer"
{
    + {abstract} virtual slot void progressNotification( const tProgressNotificationData& progressNotificationData ) = 0
    + tRequestId requestAnalyze( const tRequestParameters& requestParameters )
}

}

package "DMA_Common" #DDDDDD
{

class "CBGColorAnimation"
{
}

class "CRegexDirectoryMonitor"
{
}

class "CTableMemoryJumper"
{
}

}

package "DMA_CoverageNote_API" #DDDDDD
{

class "ICoverageNoteProvider"
{
}

}

package "DMA_FiltersView_API" #DDDDDD
{

class "CFiltersView"
{
}

class "IFiltersModel"
{
    + {abstract} virtual void addCompletionData( const tFoundMatches& foundMatches ) = 0
    + {abstract} virtual void filterRegexTokens( const QString& filter ) = 0
    + {abstract} virtual void resetCompletionData() = 0
    + {abstract} virtual void resetData() = 0
    + {abstract} virtual void setUsedRegex(const QString& regexStr) = 0
}

}

package "DMA_GroupedView_API" #DDDDDD
{

class "CGroupedView"
{
}

class "IGroupedViewModel"
{
    + {abstract} virtual int rowCount(const QModelIndex &parent = QModelIndex()) const = 0
    + {abstract} virtual std::pair<bool__QString> exportToHTML(QString& resultHTML) = 0
    + {abstract} virtual void addMatches( const tFoundMatches& matches, bool update ) = 0
    + {abstract} virtual void resetData() = 0
    + {abstract} virtual void setUsedRegex(const QString& regex) = 0
}

}

package "DMA_Log_API" #DDDDDD
{

class "CConsoleView"
{
}

}

package "DMA_Logo_API" #DDDDDD
{

class "CLogo"
{
}

}

package "DMA_LogsWrapper_API" #DDDDDD
{

class "IFileWrapper"
{
    + {abstract} virtual QString getCacheStatusAsString() const = 0
    + {abstract} virtual QString getFileName(int num = 0) = 0
    + {abstract} virtual bool cacheMsgByIndex( const tMsgId& msgId ) = 0
    + {abstract} virtual bool cacheMsgByIndexes( const QSet<tMsgId> msgIdSet ) = 0
    + {abstract} virtual bool cacheMsgByRange( const tIntRange& msgRange ) = 0
    + {abstract} virtual bool cacheMsgWrapper( const int& msgId, const tMsgWrapperPtr& pMsgWrapper ) = 0
    + {abstract} virtual bool getSubFilesHandlingStatus() const = 0
    + {abstract} virtual bool isFiltered() const = 0
    + {abstract} virtual int getMsgIdFromIndexInMainTable(int msgIdxInMainTable) const = 0
    + {abstract} virtual int getNumberOfFiles() const = 0
    + {abstract} virtual int size() const = 0
    + {abstract} virtual int sizeNonFiltered() const = 0
    + signal void currentSizeMbChanged(tCacheSizeMB MBytes)
    + signal void fullChanged(bool isFull)
    + signal void isEnabledChanged(bool isEnabled)
    + signal void loadChanged(unsigned int percents)
    + signal void maxSizeMbChanged(tCacheSizeMB MBytes)
    + {abstract} virtual tIntRangeProperty normalizeSearchRange( const tIntRangeProperty& inputRange) = 0
    + {abstract} virtual tMsgWrapperPtr getMsg(const tMsgId& msgId) = 0
    + {abstract} virtual virtual tIntRangeList getSubFilesSizeRanges() const = 0
    + {abstract} virtual void copyFileNameToClipboard( const int& msgId ) const = 0
    + {abstract} virtual void copyFileNamesToClipboard( const tIntRange& msgsRange ) const = 0
    + {abstract} virtual void resetCache() = 0
    + {abstract} virtual void setEnableCache(bool isEnabled) = 0
    + {abstract} virtual void setMaxCacheSize(const tCacheSizeB& cacheSize ) = 0
    + {abstract} virtual void setMessageDecoder( IMsgDecoder* pMessageDecoder ) = 0
    + {abstract} virtual void setSubFilesHandlingStatus(const bool& val) = 0
}

}

package "DMA_PatternsView_API" #DDDDDD
{

class "CPatternsView"
{
}

class "IPatternsModel"
{
    + {abstract} virtual QModelIndex addData(const QString& alias, const QString& regex, Qt::CheckState isCombine, Qt::CheckState isDefault) = 0
    + {abstract} virtual QModelIndex addData(const QString& alias, const QString& regex, Qt::CheckState isDefault = Qt::Unchecked) = 0
    + {abstract} virtual QModelIndex editData(const QModelIndex& idx, const QString& alias, const QString& regex, Qt::CheckState isDefault, Qt::CheckState isCombine) = 0
    + {abstract} virtual QString getAliasEditName( const QModelIndex& idx ) = 0
    + {abstract} virtual removeData(const QModelIndex& idx) = 0
    + {abstract} virtual signal void patternsRefreshed() = 0
    + {abstract} virtual tSearchResult search( const QString& alias ) = 0
    + {abstract} virtual void filterPatterns( const QString& filter ) = 0
    + {abstract} virtual void refreshRegexPatterns() = 0
    + {abstract} virtual void resetData() = 0
    + {abstract} virtual void updatePatternsInPersistency() = 0
    + {abstract} virtual void updateView() = 0
}

}

package "DMA_PlantumlView_API" #DDDDDD
{

class "CUMLView"
{
}

}

package "DMA_Plugin" #DDDDDD
{

class "DLTMessageAnalyzerPlugin"
{
}

}

package "DMA_Plugin_API" #DDDDDD
{

class "CDLTMessageAnalyzer"
{
}

class "Form"
{
}

class "Ui::Form"
{
}

}

package "DMA_RegexHistory_API" #DDDDDD
{

class "CRegexHistoryTextEdit"
{
}

}

package "DMA_SearchView_API" #DDDDDD
{

class "CSearchResultView"
{
}

class "ISearchResultModel"
{
    + {abstract} virtual int getFileIdx( const QModelIndex& idx ) const = 0
    + {abstract} virtual std::pair<bool__tIntRange> addNextMessageIdxVec(const tFoundMatchesPack& foundMatchesPack) = 0
    + {abstract} virtual std::pair<int__QString > getUMLDiagramContent() const = 0
    + {abstract} virtual tPlotContent createPlotContent() const = 0
    + {abstract} virtual void resetData() = 0
    + {abstract} virtual void setFile(const tFileWrapperPtr& pFile) = 0
    + {abstract} virtual void updateView(const int& fromRow = 0) = 0
}

}

package "DMA_Settings_API" #DDDDDD
{

class "CSettingsManagerClient"
{
}

class "ISettingsManager"
{
}

}

package "Qt" #DDDDDD
{

class "QWidget"
{
}

}

'====================Inheritance section====================
CSettingsManagerClient <|-- CDLTMessageAnalyzer : extends
IDLTMessageAnalyzerControllerConsumer <|-- CDLTMessageAnalyzer : implements
CSettingsManagerClient <|-- Form : extends
QWidget <|-- Form : extends

'====================Dependencies section====================
DLTMessageAnalyzerPlugin "1" *-- "1" CDLTMessageAnalyzer : contains
DLTMessageAnalyzerPlugin "1" *-- "1" Form : contains
CDLTMessageAnalyzer "1" --> "1" CBGColorAnimation : uses
CDLTMessageAnalyzer "1" o-- "1" CFiltersView : uses
CDLTMessageAnalyzer "1" o-- "1" CPatternsView : uses
CDLTMessageAnalyzer "1" *-- "1" CRegexDirectoryMonitor : contains
CDLTMessageAnalyzer "1" --> "1" CRegexHistoryTextEdit : uses and passes
CDLTMessageAnalyzer "1" o-- "1" CSearchResultView : uses
CDLTMessageAnalyzer "1" o-- "1" CTableMemoryJumper : gets and uses
CDLTMessageAnalyzer "1" o-- "1" CUMLView : uses
CDLTMessageAnalyzer "1" o-- "1" ICoverageNoteProvider : uses
CDLTMessageAnalyzer "1" --> "1" IDLTMessageAnalyzerController : gets and feeds to IDLTMessageAnalyzerControllerConsumer
CDLTMessageAnalyzer "1" o-- "1" IFileWrapper : uses
CDLTMessageAnalyzer "1" o-- "1" IFiltersModel : uses
CDLTMessageAnalyzer "1" *-- "1" IGroupedViewModel : uses
CDLTMessageAnalyzer "1" o-- "1" IPatternsModel : uses
CDLTMessageAnalyzer "1" o-- "1" ISearchResultModel : gets and uses
CDLTMessageAnalyzer "1" o-- "1" ISettingsManager : gets and uses
CDLTMessageAnalyzer "1" o-- "1" QDltMessageDecoder : uses
Form "1" o-- "1" DLTMessageAnalyzerPlugin : uses
Form "1" *-- "1" Ui::Form : contains
Ui::Form "1" *-- "1" CConsoleView : contains
Ui::Form "1" *-- "1" CFiltersView : contains
Ui::Form "1" *-- "1" CGroupedView : contains
Ui::Form "1" *-- "1" CLogo : contains
Ui::Form "1" *-- "1" CPatternsView : contains
Ui::Form "1" *-- "1" CRegexHistoryTextEdit : contains
Ui::Form "1" *-- "1" CSearchResultView : contains
Ui::Form "1" *-- "1" CUMLView : contains

@enduml