
@startuml

skinparam backgroundColor #FEFEFE
skinparam wrapWidth 600
package "DMA_Analyzer_API" #DDDDDD
{

class "CAnalyzerComponent"
{
}

}

package "DMA_CoverageNote_API" #DDDDDD
{

class "CCoverageNoteComponent"
{
}

}

package "DMA_FiltersView_API" #DDDDDD
{

class "CFiltersViewComponent"
{
}

}

package "DMA_Framework_Base" #DDDDDD
{

class "DMA::CBaseSynchronousInitializable"
{
    # {abstract} virtual virtual tSyncInitOperationResult init() = 0
    # {abstract} virtual virtual tSyncInitOperationResult shutdown() = 0
    + virtual virtual tSyncInitOperationResult startInit()
    + virtual virtual tSyncInitOperationResult startShutdown()
    + virtual virtual virtual bool isInitialized () const
}

class "DMA::INamedObject"
{
    + char* getName() const
}

}

package "DMA_Framework_Component" #DDDDDD
{

class "DMA::IComponent"
{
}

}

package "DMA_GroupedView_API" #DDDDDD
{

class "CGroupedViewComponent"
{
}

}

package "DMA_Log_API" #DDDDDD
{

class "CLogComponent"
{
}

}

package "DMA_Logo_API" #DDDDDD
{

class "CLogoComponent"
{
}

}

package "DMA_LogsWrapper_API" #DDDDDD
{

class "CLogsWrapperComponent"
{
}

}

package "DMA_PatternsView_API" #DDDDDD
{

class "CPatternsViewComponent"
{
}

}

package "DMA_PlantumlView_API" #DDDDDD
{

class "CUMLViewComponent"
{
}

}

package "DMA_PlotView_API" #DDDDDD
{

class "CPlotViewComponent"
{
}

}

package "DMA_RegexHistory_API" #DDDDDD
{

class "CRegexHistoryComponent"
{
}

}

package "DMA_SearchView_API" #DDDDDD
{

class "CSearchViewComponent"
{
}

}

package "DMA_Settings_API" #DDDDDD
{

class "CSettingsComponent"
{
}

}

'====================Inheritance section====================
DMA::IComponent <|-- CAnalyzerComponent : implements
DMA::IComponent <|-- CCoverageNoteComponent : implements
DMA::IComponent <|-- CFiltersViewComponent : implements
DMA::CBaseSynchronousInitializable <|-- DMA::IComponent : extends
DMA::INamedObject <|-- DMA::IComponent : implements
DMA::IComponent <|-- CGroupedViewComponent : implements
DMA::IComponent <|-- CLogComponent : implements
DMA::IComponent <|-- CLogoComponent : implements
DMA::IComponent <|-- CLogsWrapperComponent : implements
DMA::IComponent <|-- CPatternsViewComponent : implements
DMA::IComponent <|-- CUMLViewComponent : implements
DMA::IComponent <|-- CPlotViewComponent : implements
DMA::IComponent <|-- CRegexHistoryComponent : implements
DMA::IComponent <|-- CSearchViewComponent : implements
DMA::IComponent <|-- CSettingsComponent : implements

@enduml