
@startuml

skinparam backgroundColor #FEFEFE
skinparam wrapWidth 600
package "DMA_Logo" #DDDDDD
{

class "CLogo"
{
}

}

package "DMA_Root" #DDDDDD
{

class "Ui::Form"
{
}

}

package "Qt" #DDDDDD
{

class "QPushButton"
{
}

}

'====================Inheritance section====================
QPushButton <|-- CLogo : extends

'====================Dependencies section====================
Ui::Form "1" *-- "1" CLogo : contains

@enduml