
@startuml

skinparam wrapWidth 600
package "DMA_Log" #DDDDDD
{

class "CConsoleCtrl"<< (S,#FF7700) Singleton >>
{
}

class "CConsoleInputProcessor"
{
}

class "CConsoleView"
{
}

}

package "Qt" #DDDDDD
{

class "QObject"
{
}

class "QPlainTextEdit"
{
}

}

'====================Inheritance section====================
QObject <|-- CConsoleCtrl : extends
QObject <|-- CConsoleInputProcessor : extends
QPlainTextEdit <|-- CConsoleView : extends

@enduml