
@startuml

skinparam wrapWidth 600
package "DMA_PatternsView" #DDDDDD
{

class "CPatternsModel"
{
}

class "CPatternsView"
{
}

class "CTreeRepresentationDelegate"
{
}

}

package "Qt" #DDDDDD
{

abstract class "QAbstractItemModel"
{
}

class "QStyledItemDelegate"
{
}

class "QTreeView"
{
}

}

'====================Inheritance section====================
QAbstractItemModel <|-- CPatternsModel : implements
QTreeView <|-- CPatternsView : extends
QStyledItemDelegate <|-- CTreeRepresentationDelegate : extends

'====================Dependencies section====================
CPatternsView "1" o-- "1" CPatternsModel : uses
CPatternsView "1" *-- "1" CTreeRepresentationDelegate : contains

@enduml