
@startuml

skinparam wrapWidth 600
package "DMA_PlantUML" #DDDDDD
{

class "CImageViewer"
{
}

class "CUMLView"
{
}

}

package "Qt" #DDDDDD
{

class "QWidget"
{
}

}

'====================Inheritance section====================
QWidget <|-- CImageViewer : extends
QWidget <|-- CUMLView : extends

'====================Dependencies section====================
CUMLView "1" *-- "1" CImageViewer : contains

@enduml