
@startuml

skinparam backgroundColor #FEFEFE
skinparam wrapWidth 600
package "DMA_Analyzer" #DDDDDD
{

class "CContinuousAnalyzer"
{
}

class "CDLTRegexAnalyzerWorker"
{
}

class "CMTAnalyzer"
{
}

class "CSubConsumer"
{
}

}

package "DMA_Analyzer_API" #DDDDDD
{

abstract class "IDLTMessageAnalyzerController"
{
    + {abstract} virtual int getMaximumNumberOfThreads() const = 0
    + {abstract} virtual tRequestId requestAnalyze( const std::weak_ptr<IDLTMessageAnalyzerControllerConsumer>& pClient, const tFileWrapperPtr& pFile, const int& fromMessage, const int& numberOfMessages, const QRegularExpression& regex, const int& numberOfThreads, const tRegexScriptingMetadata& regexScriptingMetadata, bool isContinuous) = 0
    + {abstract} virtual void cancelRequest( const std::weak_ptr<IDLTMessageAnalyzerControllerConsumer>& pClient, const tRequestId& requestId ) = 0
}

abstract class "IDLTMessageAnalyzerControllerConsumer"
{
    + tRequestId requestAnalyze( const tFileWrapperPtr& pFile, const int& fromMessage, const int& numberOfMessages, const QRegularExpression& regex, const int& numberOfThreads, bool isContinuous )
    + {abstract} virtual void progressNotification( const tRequestId& requestId, const eRequestState& requestState, const int8_t& progress, const tFoundMatchesPack& processedMatches) = 0
}

}

package "DMA_Settings_API" #DDDDDD
{

class "CSettingsManagerClient"
{
}

}

package "Qt" #DDDDDD
{

class "QObject"
{
}

}

'====================Inheritance section====================
IDLTMessageAnalyzerController <|-- CContinuousAnalyzer : implements
CSettingsManagerClient <|-- CDLTRegexAnalyzerWorker : extends
QObject <|-- CDLTRegexAnalyzerWorker : extends
CSettingsManagerClient <|-- CMTAnalyzer : extends
IDLTMessageAnalyzerController <|-- CMTAnalyzer : implements
IDLTMessageAnalyzerControllerConsumer <|-- CSubConsumer : implements

'====================Dependencies section====================
CMTAnalyzer "1" *-- "*" CDLTRegexAnalyzerWorker : contains

@enduml