
@startuml

skinparam backgroundColor #FEFEFE
skinparam wrapWidth 600
package "DLT" #DDDDDD
{

interface "QDLTPluginInterface"
{
}

class "QDltFile"
{
}

class "QDltMsg"
{
}

class "QDltPlugin"
{
}

interface "QDltPluginControlInterface"
{
}

class "QDltPluginManager"
{
}

interface "QDltPluginViewerInterface"
{
}

}

package "DMA_Analyzer" #DDDDDD
{

class "CContinuousAnalyzer"
{
}

class "CDLTRegexAnalyzerWorker"
{
}

class "CMTAnalyzer"
{
}

class "CSubConsumer"
{
}

}

package "DMA_Analyzer_API" #DDDDDD
{

class "CAnalyzerComponent"
{
}

abstract class "IDLTMessageAnalyzerController"
{
    + {abstract} virtual int getMaximumNumberOfThreads() const = 0
    + signal void progressNotification( const tProgressNotificationData& progressNotificationData )
    + {abstract} virtual tRequestId requestAnalyze( const std::weak_ptr<IDLTMessageAnalyzerControllerConsumer>& pClient, const tRequestParameters& requestParameters ) = 0
    + {abstract} virtual void cancelRequest( const std::weak_ptr<IDLTMessageAnalyzerControllerConsumer>& pClient, const tRequestId& requestId ) = 0
}

abstract class "IDLTMessageAnalyzerControllerConsumer"
{
    + {abstract} virtual slot void progressNotification( const tProgressNotificationData& progressNotificationData ) = 0
    + tRequestId requestAnalyze( const tRequestParameters& requestParameters )
}

class "std::enable_shared_from_this<IDLTMessageAnalyzerControllerConsumer>" as std::enable_shared_from_this_IDLTMessageAnalyzerControllerConsumer_
{
}

}

package "DMA_Common" #DDDDDD
{

class "CBGColorAnimation"
{
}

class "CRegexDirectoryMonitor"
{
}

class "CTableMemoryJumper"
{
}

class "CTreeItem"
{
}

}

package "DMA_FiltersView" #DDDDDD
{

class "CFilterItemDelegate"
{
}

class "CFiltersModel"
{
}

}

package "DMA_FiltersView_API" #DDDDDD
{

class "CFiltersView"
{
}

class "CFiltersViewComponent"
{
}

class "IFiltersModel"
{
    + {abstract} virtual void addCompletionData( const tFoundMatches& foundMatches ) = 0
    + {abstract} virtual void filterRegexTokens( const QString& filter ) = 0
    + {abstract} virtual void resetCompletionData() = 0
    + {abstract} virtual void resetData() = 0
    + {abstract} virtual void setUsedRegex(const QString& regexStr) = 0
}

}

package "DMA_Framework_Base" #DDDDDD
{

class "DMA::CBaseSynchronousInitializable"
{
    # {abstract} virtual virtual tSyncInitOperationResult init() = 0
    # {abstract} virtual virtual tSyncInitOperationResult shutdown() = 0
    + virtual virtual tSyncInitOperationResult startInit()
    + virtual virtual tSyncInitOperationResult startShutdown()
    + virtual virtual virtual bool isInitialized () const
}

class "DMA::INamedObject"
{
    + char* getName() const
}

class "DMA::ISynchronousInitializable"
{
    + {abstract} virtual virtual tSyncInitOperationResult startInit() = 0
    + {abstract} virtual virtual tSyncInitOperationResult startShutdown() = 0
    + {abstract} virtual virtual virtual bool isInitialized () const = 0
}

}

package "DMA_Framework_Component" #DDDDDD
{

class "DMA::IComponent"
{
}

}

package "DMA_GroupedView" #DDDDDD
{

class "CGroupedViewModel"
{
}

}

package "DMA_GroupedView_API" #DDDDDD
{

class "CGroupedView"
{
}

class "CGroupedViewComponent"
{
}

class "IGroupedViewModel"
{
    + {abstract} virtual int rowCount(const QModelIndex &parent = QModelIndex()) const = 0
    + {abstract} virtual std::pair<bool__QString> exportToHTML(QString& resultHTML) = 0
    + {abstract} virtual void addMatches( const tFoundMatches& matches, bool update ) = 0
    + {abstract} virtual void resetData() = 0
    + {abstract} virtual void setUsedRegex(const QString& regex) = 0
}

}

package "DMA_Log" #DDDDDD
{

class "CConsoleCtrl"<< (S,#FF7700) Singleton >>
{
}

class "CConsoleInputProcessor"
{
}

}

package "DMA_Log_API" #DDDDDD
{

class "CConsoleView"
{
}

class "CLogComponent"
{
}

}

package "DMA_Logo_API" #DDDDDD
{

class "CLogo"
{
}

class "CLogoComponent"
{
}

}

package "DMA_LogsWrapper" #DDDDDD
{

class "CDLTFileWrapper"
{
}

class "CDLTMsgDecoder"
{
}

class "CDLTMsgWrapper"
{
}

}

package "DMA_LogsWrapper_API" #DDDDDD
{

class "CLogsWrapperComponent"
{
}

class "IDLTLogsWrapperCreator"
{
    + {abstract} virtual tFileWrapperPtr createDLTFileWrapper( QDltFile* pFile ) const = 0
    + {abstract} virtual tMsgDecoderPtr createMsgDecoder(const tPluginPtrList& decoderPlugins) const = 0
    + {abstract} virtual tMsgWrapperPtr createDLTMsgWrapper( QDltMsg& msg ) const = 0
}

class "IFileWrapper"
{
    + {abstract} virtual QString getCacheStatusAsString() const = 0
    + {abstract} virtual QString getFileName(int num = 0) = 0
    + {abstract} virtual bool cacheMsgByIndex( const tMsgId& msgId ) = 0
    + {abstract} virtual bool cacheMsgByIndexes( const QSet<tMsgId> msgIdSet ) = 0
    + {abstract} virtual bool cacheMsgByRange( const tIntRange& msgRange ) = 0
    + {abstract} virtual bool cacheMsgWrapper( const int& msgId, const tMsgWrapperPtr& pMsgWrapper ) = 0
    + {abstract} virtual bool getSubFilesHandlingStatus() const = 0
    + {abstract} virtual bool isFiltered() const = 0
    + {abstract} virtual int getMsgRealPos(int msgId) const = 0
    + {abstract} virtual int getNumberOfFiles() const = 0
    + {abstract} virtual int size() const = 0
    + {abstract} virtual int sizeNonFiltered() const = 0
    + signal void currentSizeMbChanged(tCacheSizeMB MBytes)
    + signal void fullChanged(bool isFull)
    + signal void isEnabledChanged(bool isEnabled)
    + signal void loadChanged(unsigned int percents)
    + signal void maxSizeMbChanged(tCacheSizeMB MBytes)
    + {abstract} virtual tIntRangeProperty normalizeSearchRange( const tIntRangeProperty& inputRange) = 0
    + {abstract} virtual tMsgWrapperPtr getMsg(const tMsgId& msgId) = 0
    + {abstract} virtual virtual tIntRangeList getSubFilesSizeRanges() const = 0
    + {abstract} virtual void copyFileNameToClipboard( const int& msgId ) const = 0
    + {abstract} virtual void copyFileNamesToClipboard( const tIntRange& msgsRange ) const = 0
    + {abstract} virtual void resetCache() = 0
    + {abstract} virtual void setEnableCache(bool isEnabled) = 0
    + {abstract} virtual void setMaxCacheSize(const tCacheSizeB& cacheSize ) = 0
    + {abstract} virtual void setMessageDecoder( IMsgDecoder* pMessageDecoder ) = 0
    + {abstract} virtual void setSubFilesHandlingStatus(const bool& val) = 0
}

class "IMsgDecoder"
{
    + {abstract} virtual void decodeMsg(QDltMsg&, int) = 0
}

class "IMsgWrapper"
{
    + {abstract} virtual QString getApid() const = 0
    + {abstract} virtual QString getCtid() const = 0
    + {abstract} virtual QString getCtrlReturnTypeString() const = 0
    + {abstract} virtual QString getCtrlServiceIdString() const = 0
    + {abstract} virtual QString getEcuid() const = 0
    + {abstract} virtual QString getModeString() const = 0
    + {abstract} virtual QString getPayload() const = 0
    + {abstract} virtual QString getSubtypeString() const = 0
    + {abstract} virtual QString getTimeString() const = 0
    + {abstract} virtual QString getTypeString() const = 0
    + {abstract} virtual const unsigned char& getMessageCounter() const = 0
    + {abstract} virtual const unsigned int& getMicroseconds() const = 0
    + {abstract} virtual const unsigned int& getNumberOfArguments() const = 0
    + {abstract} virtual const unsigned int& getSessionid() const = 0
    + {abstract} virtual const unsigned int& getTimestamp() const = 0
    + {abstract} virtual unsigned int getInitialMessageSize() const = 0
    + {abstract} virtual unsigned int getSize() const = 0
    + {abstract} virtual void dumpPayload() const = 0
    + {abstract} virtual void dumpSize() const = 0
}

}

package "DMA_PatternsView" #DDDDDD
{

class "CPatternsModel"
{
}

}

package "DMA_PatternsView_API" #DDDDDD
{

class "CPatternsView"
{
}

class "CPatternsViewComponent"
{
}

class "CTreeRepresentationDelegate"
{
}

class "IPatternsModel"
{
    + {abstract} virtual QModelIndex addData(const QString& alias, const QString& regex, Qt::CheckState isCombine, Qt::CheckState isDefault) = 0
    + {abstract} virtual QModelIndex addData(const QString& alias, const QString& regex, Qt::CheckState isDefault = Qt::Unchecked) = 0
    + {abstract} virtual QModelIndex editData(const QModelIndex& idx, const QString& alias, const QString& regex, Qt::CheckState isDefault, Qt::CheckState isCombine) = 0
    + {abstract} virtual QString getAliasEditName( const QModelIndex& idx ) = 0
    + {abstract} virtual removeData(const QModelIndex& idx) = 0
    + {abstract} virtual signal void patternsRefreshed() = 0
    + {abstract} virtual tSearchResult search( const QString& alias ) = 0
    + {abstract} virtual void filterPatterns( const QString& filter ) = 0
    + {abstract} virtual void refreshRegexPatterns() = 0
    + {abstract} virtual void resetData() = 0
    + {abstract} virtual void updatePatternsInPersistency() = 0
    + {abstract} virtual void updateView() = 0
}

}

package "DMA_PlantumlView" #DDDDDD
{

class "CImageViewer"
{
}

}

package "DMA_PlantumlView_API" #DDDDDD
{

class "CUMLView"
{
}

class "CUMLViewComponent"
{
}

}

package "DMA_Plugin" #DDDDDD
{

class "DLTMessageAnalyzerPlugin"
{
}

}

package "DMA_Plugin_API" #DDDDDD
{

class "CDLTMessageAnalyzer"
{
}

class "Form"
{
}

class "Ui::Form"
{
}

}

package "DMA_SearchView" #DDDDDD
{

class "CSearchResultHighlightingDelegate"
{
}

class "CSearchResultModel"
{
}

}

package "DMA_SearchView_API" #DDDDDD
{

class "CSearchResultView"
{
}

class "CSearchViewComponent"
{
}

class "ISearchResultModel"
{
    + {abstract} virtual int getFileIdx( const QModelIndex& idx ) const = 0
    + {abstract} virtual std::pair<bool__tIntRange> addNextMessageIdxVec(const tFoundMatchesPack& foundMatchesPack) = 0
    + {abstract} virtual std::pair<int__QString > getUMLDiagramContent() const = 0
    + {abstract} virtual void resetData() = 0
    + {abstract} virtual void setFile(const tFileWrapperPtr& pFile) = 0
    + {abstract} virtual void updateView(const int& fromRow = 0) = 0
}

}

package "DMA_Settings" #DDDDDD
{

abstract class "CSettingItem"
{
    + virtual const QString& getKey() override
    + virtual const tUpdateSettingsFileFunc& getUpdateFileFunc() override
}

class "CSettingsManager"
{
}

abstract class "ISettingItem"
{
    + {abstract} virtual QJsonObject writeData() const = 0
    + {abstract} virtual bool readData( const QJsonValueRef& setting ) = 0
    + {abstract} virtual const QString& getKey() = 0
    + {abstract} virtual const tUpdateSettingsFileFunc& getUpdateFileFunc() = 0
    + {abstract} virtual tGeneralUpdateDataFunc getGeneralUpdateDataFunc() = 0
}

class "TSettingItem<T>" as TSettingItem_T_
{
    + virtual QJsonObject writeData() const override
    + virtual bool readData( const QJsonValueRef& setting ) override
    + virtual tGeneralUpdateDataFunc getGeneralUpdateDataFunc() override
}

}

package "DMA_Settings_API" #DDDDDD
{

class "CSettingsComponent"
{
}

class "CSettingsManagerClient"
{
}

class "ISettingsManager"
{
}

}

package "Qt" #DDDDDD
{

abstract class "QAbstractItemModel"
{
}

abstract class "QAbstractTableModel"
{
}

class "QCompleter"
{
}

class "QElapsedTimer"
{
}

class "QFileSystemWatcher"
{
}

class "QImage"
{
}

class "QLineEdit"
{
}

class "QObject"
{
}

class "QPlainTextEdit"
{
}

class "QProcess"
{
}

class "QPushButton"
{
}

class "QStyledItemDelegate"
{
}

class "QTabWidget"
{
}

class "QTableView"
{
}

class "QThread"
{
}

class "QTimer"
{
}

class "QTreeView"
{
}

class "QWidget"
{
}

}

'====================Inheritance section====================
IDLTMessageAnalyzerController <|-- CContinuousAnalyzer : implements
CSettingsManagerClient <|-- CDLTRegexAnalyzerWorker : extends
QObject <|-- CDLTRegexAnalyzerWorker : extends
CSettingsManagerClient <|-- CMTAnalyzer : extends
IDLTMessageAnalyzerController <|-- CMTAnalyzer : implements
IDLTMessageAnalyzerControllerConsumer <|-- CSubConsumer : implements
CSettingsManagerClient <|-- CAnalyzerComponent : extends
DMA::IComponent <|-- CAnalyzerComponent : implements
QObject <|-- IDLTMessageAnalyzerController : extends
QObject <|-- IDLTMessageAnalyzerControllerConsumer : extends
std::enable_shared_from_this_IDLTMessageAnalyzerControllerConsumer_ <|-- IDLTMessageAnalyzerControllerConsumer : extends
QObject <|-- CBGColorAnimation : extends
QObject <|-- CRegexDirectoryMonitor : extends
CSettingsManagerClient <|-- CFilterItemDelegate : extends
QStyledItemDelegate <|-- CFilterItemDelegate : extends
CSettingsManagerClient <|-- CFiltersModel : extends
IFiltersModel <|-- CFiltersModel : implements
CSettingsManagerClient <|-- CFiltersView : extends
QTreeView <|-- CFiltersView : implements
CSettingsManagerClient <|-- CFiltersViewComponent : extends
DMA::IComponent <|-- CFiltersViewComponent : implements
QAbstractItemModel <|-- IFiltersModel : implements
DMA::ISynchronousInitializable <|-- DMA::CBaseSynchronousInitializable : implements
DMA::CBaseSynchronousInitializable <|-- DMA::IComponent : extends
DMA::INamedObject <|-- DMA::IComponent : implements
CSettingsManagerClient <|-- CGroupedViewModel : extends
IGroupedViewModel <|-- CGroupedViewModel : implements
QAbstractItemModel <|-- CGroupedViewModel : implements
CSettingsManagerClient <|-- CGroupedView : extends
QTreeView <|-- CGroupedView : extends
CSettingsManagerClient <|-- CGroupedViewComponent : extends
DMA::IComponent <|-- CGroupedViewComponent : implements
QObject <|-- CConsoleCtrl : extends
QObject <|-- CConsoleInputProcessor : extends
QPlainTextEdit <|-- CConsoleView : extends
DMA::IComponent <|-- CLogComponent : implements
QPushButton <|-- CLogo : extends
DMA::IComponent <|-- CLogoComponent : implements
IFileWrapper <|-- CDLTFileWrapper : implements
IMsgDecoder <|-- CDLTMsgDecoder : implements
IMsgWrapper <|-- CDLTMsgWrapper : implements
DMA::IComponent <|-- CLogsWrapperComponent : implements
IDLTLogsWrapperCreator <|-- CLogsWrapperComponent : implements
QObject <|-- IFileWrapper : extends
CSettingsManagerClient <|-- CPatternsModel : extends
IPatternsModel <|-- CPatternsModel : implements
CSettingsManagerClient <|-- CPatternsView : extends
QTreeView <|-- CPatternsView : extends
CSettingsManagerClient <|-- CPatternsViewComponent : extends
DMA::IComponent <|-- CPatternsViewComponent : implements
QStyledItemDelegate <|-- CTreeRepresentationDelegate : extends
QAbstractItemModel <|-- IPatternsModel : implements
QWidget <|-- CImageViewer : extends
CSettingsManagerClient <|-- CUMLView : extends
QWidget <|-- CUMLView : extends
CSettingsManagerClient <|-- CUMLViewComponent : extends
DMA::IComponent <|-- CUMLViewComponent : implements
QDLTPluginInterface <|-- DLTMessageAnalyzerPlugin : implements
QDltPluginControlInterface <|-- DLTMessageAnalyzerPlugin : implements
QDltPluginViewerInterface <|-- DLTMessageAnalyzerPlugin : implements
QObject <|-- DLTMessageAnalyzerPlugin : extends
CSettingsManagerClient <|-- CDLTMessageAnalyzer : extends
IDLTMessageAnalyzerControllerConsumer <|-- CDLTMessageAnalyzer : implements
CSettingsManagerClient <|-- Form : extends
QWidget <|-- Form : extends
CSettingsManagerClient <|-- CSearchResultHighlightingDelegate : extends
QStyledItemDelegate <|-- CSearchResultHighlightingDelegate : extends
CSettingsManagerClient <|-- CSearchResultModel : extends
ISearchResultModel <|-- CSearchResultModel : implements
QAbstractTableModel <|-- CSearchResultModel : implements
QTableView <|-- CSearchResultView : extends
CSettingsManagerClient <|-- CSearchViewComponent : extends
DMA::IComponent <|-- CSearchViewComponent : implements
QObject <|-- CSearchViewComponent : extends
ISettingItem <|-- CSettingItem : partially implements
ISettingsManager <|-- CSettingsManager : implements
CSettingItem <|-- TSettingItem_T_ : extends
DMA::IComponent <|-- CSettingsComponent : implements
QObject <|-- ISettingsManager : extends

'====================Dependencies section====================
CContinuousAnalyzer "1" o-- "1" IDLTMessageAnalyzerController : uses
CContinuousAnalyzer "1" *-- "1" IDLTMessageAnalyzerControllerConsumer : contains
CMTAnalyzer "1" *-- "*" CDLTRegexAnalyzerWorker : contains
CMTAnalyzer "1" *-- "*" QThread : contains
CAnalyzerComponent "1" *-- "1" CContinuousAnalyzer : contains
CAnalyzerComponent "1" --> "1" CMTAnalyzer : creates and feeds into CContinuousAnalyzer
IDLTMessageAnalyzerController "1" --> "1" IFileWrapper : uses
IDLTMessageAnalyzerControllerConsumer "1" o-- "1" IDLTMessageAnalyzerController : uses
IDLTMessageAnalyzerControllerConsumer "1" --> "1" IFileWrapper : uses
CBGColorAnimation "1" o-- "1" QWidget : animation widget
CRegexDirectoryMonitor "1" *-- "1" QFileSystemWatcher : contains
CTableMemoryJumper "1" o-- "1" QTableView : contains
CTreeItem "1" *-- "*" CTreeItem : contains
CFilterItemDelegate "1" o-- "1" CFiltersModel : uses
CFilterItemDelegate "1" o-- "1" QCompleter : uses
CFilterItemDelegate "1" o-- "1" QTreeView : parent view
CFiltersModel "1" *-- "*" CTreeItem : contains
CFiltersView "1" *-- "1" CFilterItemDelegate : contains
CFiltersView "1" o-- "1" CFiltersModel : uses
CFiltersView "1" o-- "1" QLineEdit : regex input field
CFiltersViewComponent "1" --> "1" CFiltersModel : using to create IFiltersModel
CFiltersViewComponent "1" o-- "1" CFiltersView : uses
CFiltersViewComponent "1" *-- "1" IFiltersModel : contains
CGroupedViewModel "1" *-- "*" CTreeItem : contains
CGroupedViewComponent "1" o-- "1" CGroupedView : uses
CGroupedViewComponent "1" --> "1" CGroupedViewModel : using to create IGroupedViewModel
CGroupedViewComponent "1" *-- "1" IGroupedViewModel : contains
CConsoleCtrl "1" o-- "1" QPlainTextEdit : console text edit
CConsoleCtrl "1" o-- "1" QTabWidget : console view tab widget
CConsoleCtrl "1" o-- "1" QWidget : console tab
CConsoleInputProcessor "1" o-- "1" QLineEdit : console input
CLogComponent "1" *-- "1" CConsoleInputProcessor : contains
CLogoComponent "1" o-- "1" CLogo : uses
CDLTFileWrapper "1" --> "*" CDLTMsgWrapper : creates
CDLTFileWrapper "1" *-- "*" IMsgWrapper : cache
CDLTFileWrapper "1" o-- "1" QDltFile : uses
CDLTMsgDecoder "1" o-- "1" QDltMsg : uses
CDLTMsgWrapper "1" --> "1" QDltMsg : uses
CLogsWrapperComponent "1" --> "*" CDLTFileWrapper : creates instances
CLogsWrapperComponent "1" --> "*" CDLTMsgDecoder : creates instances
CLogsWrapperComponent "1" --> "*" CDLTMsgWrapper : creates instances
IDLTLogsWrapperCreator "1" --> "*" IFileWrapper : creates
IDLTLogsWrapperCreator "1" --> "*" IMsgDecoder : creates
IDLTLogsWrapperCreator "1" --> "*" IMsgWrapper : creates
IDLTLogsWrapperCreator "1" --> "*" QDltFile : uses
IDLTLogsWrapperCreator "1" --> "*" QDltMsg : uses
IDLTLogsWrapperCreator "1" --> "*" QDltPlugin : uses
IFileWrapper "1" --> "1" IMsgDecoder : uses
IFileWrapper "1" --> "1" IMsgWrapper : provides
CPatternsModel "1" *-- "*" CTreeItem : contains
CPatternsView "1" o-- "1" CPatternsModel : uses
CPatternsView "1" *-- "1" CTreeRepresentationDelegate : contains
CPatternsView "1" o-- "1" QLineEdit : patterns search input
CPatternsViewComponent "1" --> "1" CPatternsModel : using to create IPatternsModel
CPatternsViewComponent "1" o-- "1" CPatternsView : uses
CPatternsViewComponent "1" *-- "1" IPatternsModel : contains
CImageViewer "1" *-- "1" QImage : contains
CUMLView "1" *-- "1" CImageViewer : contains
CUMLView "1" *-- "2" QProcess : contains
CUMLViewComponent "1" o-- "1" CUMLView : uses
DLTMessageAnalyzerPlugin "1" *-- "1" CAnalyzerComponent : contains
DLTMessageAnalyzerPlugin "1" *-- "1" CDLTMessageAnalyzer : contains
DLTMessageAnalyzerPlugin "1" *-- "1" CFiltersViewComponent : contains
DLTMessageAnalyzerPlugin "1" *-- "1" CGroupedViewComponent : contains
DLTMessageAnalyzerPlugin "1" *-- "1" CLogComponent : contains
DLTMessageAnalyzerPlugin "1" *-- "1" CLogoComponent : contains
DLTMessageAnalyzerPlugin "1" *-- "1" CLogsWrapperComponent : contains
DLTMessageAnalyzerPlugin "1" *-- "1" CPatternsViewComponent : contains
DLTMessageAnalyzerPlugin "1" *-- "1" CSearchViewComponent : contains
DLTMessageAnalyzerPlugin "1" *-- "1" CUMLViewComponent : contains
DLTMessageAnalyzerPlugin "1" *-- "1" Form : contains
CDLTMessageAnalyzer "1" --> "1" CBGColorAnimation : uses
CDLTMessageAnalyzer "1" o-- "1" CFiltersView : uses
CDLTMessageAnalyzer "1" o-- "1" CPatternsView : uses
CDLTMessageAnalyzer "1" *-- "1" CRegexDirectoryMonitor : contains
CDLTMessageAnalyzer "1" o-- "1" CSearchResultView : uses
CDLTMessageAnalyzer "1" o-- "1" CTableMemoryJumper : gets and uses
CDLTMessageAnalyzer "1" o-- "1" CUMLView : uses
CDLTMessageAnalyzer "1" --> "1" IDLTMessageAnalyzerController : gets and feeds to IDLTMessageAnalyzerControllerConsumer
CDLTMessageAnalyzer "1" o-- "1" IFileWrapper : uses
CDLTMessageAnalyzer "1" o-- "1" IFiltersModel : uses
CDLTMessageAnalyzer "1" *-- "1" IGroupedViewModel : uses
CDLTMessageAnalyzer "1" o-- "1" IPatternsModel : uses
CDLTMessageAnalyzer "1" o-- "1" ISearchResultModel : gets and uses
CDLTMessageAnalyzer "1" o-- "1" ISettingsManager : gets and uses
CDLTMessageAnalyzer "1" o-- "many" QDltPlugin : uses
CDLTMessageAnalyzer "1" *-- "1" QDltPluginManager : contains
Form "1" o-- "1" DLTMessageAnalyzerPlugin : uses
Form "1" *-- "1" Ui::Form : contains
Ui::Form "1" *-- "1" CConsoleView : contains
Ui::Form "1" *-- "1" CFiltersView : contains
Ui::Form "1" *-- "1" CGroupedView : contains
Ui::Form "1" *-- "1" CLogo : contains
Ui::Form "1" *-- "1" CPatternsView : contains
Ui::Form "1" *-- "1" CSearchResultView : contains
Ui::Form "1" *-- "1" CUMLView : contains
CSearchResultHighlightingDelegate "1" *-- "1" CSearchResultModel : uses
CSearchResultModel "1" o-- "1" IFileWrapper : uses
CSearchResultView "1" o-- "1" CSearchResultModel : uses
CSearchResultView "1" o-- "1" IFileWrapper : uses
CSearchViewComponent "1" --> "1" CSearchResultModel : using to create ISearchResultModel
CSearchViewComponent "1" o-- "1" CSearchResultView : uses
CSearchViewComponent "1" *-- "1" CTableMemoryJumper : contains
CSearchViewComponent "1" *-- "1" ISearchResultModel : contains
CSettingsManager "1" *-- "*" TSettingItem_T_ : contains
CSettingsComponent "1" --> "1" CSettingsManager : creates
CSettingsComponent "1" *-- "1" ISettingsManager : provides
CSettingsManagerClient "1" o-- "1" ISettingsManager : uses

@enduml