
@startuml

skinparam backgroundColor #FEFEFE
skinparam wrapWidth 600
package "DMA_PlotView" #DDDDDD
{

class "CScrollableLegend"
{
}

class "QCPGanttBarsData"
{
}

class "QCPGanttRow"
{
}

}

package "qcustomplot" #DDDDDD
{

class "QCPLegend"
{
}

}

'====================Inheritance section====================
QCPLegend <|-- CScrollableLegend : extends
QCPAbstractPlottable1D_QCPGanttBarsData_ <|-- QCPGanttRow : extends

'====================Dependencies section====================
QCPGanttRow "1" *-- "many" QCPGanttBarsData : contains

@enduml