
@startuml

skinparam wrapWidth 600
package "DLT" #DDDDDD
{

interface "QDLTPluginInterface"
{
}

interface "QDltPluginControlInterface"
{
}

interface "QDltPluginViewerInterface"
{
}

}

package "DMA_Analyzer" #DDDDDD
{

abstract class "IDLTMessageAnalyzerControllerConsumer"
{
    + tRequestId requestAnalyze( const tDLTFileWrapperPtr& pFile, const int& fromMessage, const int& numberOfMessages, const QRegularExpression& regex, const int& numberOfThreads, bool isContinuous )
    + {abstract} virtual void progressNotification( const tRequestId& requestId, const eRequestState& requestState, const int8_t& progress, const tFoundMatchesPack& processedMatches) = 0
}

}

package "DMA_Root" #DDDDDD
{

class "CDLTMessageAnalyzer"
{
}

class "DLTMessageAnalyzerPlugin"
{
}

class "Form"
{
}

class "Ui::Form"
{
}

}

package "Qt" #DDDDDD
{

class "QObject"
{
}

class "QWidget"
{
}

}

'====================Inheritance section====================
IDLTMessageAnalyzerControllerConsumer <|-- CDLTMessageAnalyzer : implements
QDLTPluginInterface <|-- DLTMessageAnalyzerPlugin : implements
QDltPluginControlInterface <|-- DLTMessageAnalyzerPlugin : implements
QDltPluginViewerInterface <|-- DLTMessageAnalyzerPlugin : implements
QObject <|-- DLTMessageAnalyzerPlugin : extends
QWidget <|-- Form : extends

'====================Dependencies section====================
DLTMessageAnalyzerPlugin "1" *-- "1" CDLTMessageAnalyzer : contains
DLTMessageAnalyzerPlugin "1" *-- "1" Form : contains
Form "1" o-- "1" DLTMessageAnalyzerPlugin : uses
Form "1" *-- "1" Ui::Form : contains

@enduml