
@startuml

skinparam backgroundColor #FEFEFE
skinparam wrapWidth 600
package "DMA_Log" #DDDDDD
{

class "CConsoleCtrl"<< (S,#FF7700) Singleton >>
{
}

class "CConsoleInputProcessor"
{
}

}

package "DMA_Log_API" #DDDDDD
{

class "CLogComponent"
{
}

}

package "Qt" #DDDDDD
{

class "QLineEdit"
{
}

class "QObject"
{
}

class "QPlainTextEdit"
{
}

class "QTabWidget"
{
}

class "QWidget"
{
}

}

'====================Inheritance section====================
QObject <|-- CConsoleCtrl : extends
QObject <|-- CConsoleInputProcessor : extends

'====================Dependencies section====================
CConsoleCtrl "1" o-- "1" QPlainTextEdit : console text edit
CConsoleCtrl "1" o-- "1" QTabWidget : console view tab widget
CConsoleCtrl "1" o-- "1" QWidget : console tab
CConsoleInputProcessor "1" o-- "1" QLineEdit : console input
CLogComponent "1" *-- "1" CConsoleInputProcessor : contains

@enduml