
@startuml

skinparam backgroundColor #FEFEFE
skinparam wrapWidth 600
package "Qt" #DDDDDD
{

class "QObject"
{
}

class "QWidget"
{
}

}

package "qcustomplot" #DDDDDD
{

class "QCPAxisRect"
{
}

class "QCPGraph"
{
}

class "QCPLegend"
{
}

class "QCustomPlot"
{
}

}

'====================Inheritance section====================
QObject <|-- QCPAxisRect : extends
QObject <|-- QCPGraph : extends
QObject <|-- QCPLegend : extends
QWidget <|-- QCustomPlot : extends

@enduml