
@startuml

skinparam backgroundColor #FEFEFE
skinparam wrapWidth 600
package "DMA_PlotView" #DDDDDD
{

class "CScrollableLegend"
{
}

class "QCPGanttRow"
{
}

}

package "DMA_PlotView_API" #DDDDDD
{

class "CCustomPlotExtended"
{
}

}

package "Qt" #DDDDDD
{

class "QObject"
{
}

class "QWidget"
{
}

}

package "qcustomplot" #DDDDDD
{

class "QCPAxis"
{
}

class "QCPAxisRect"
{
}

class "QCPGraph"
{
}

class "QCPLayerable"
{
}

class "QCPLegend"
{
}

class "QCustomPlot"
{
}

}

'====================Inheritance section====================
QCPLegend <|-- CScrollableLegend : extends
QCustomPlot <|-- CCustomPlotExtended : extends
QCPLayerable <|-- QCPAxis : extends
QObject <|-- QCPAxisRect : extends
QObject <|-- QCPGraph : extends
QObject <|-- QCPLayerable : extends
QObject <|-- QCPLegend : extends
QWidget <|-- QCustomPlot : extends

'====================Dependencies section====================
QCPGanttRow "1" o-- "2" QCPAxis : uses
CCustomPlotExtended "1" *-- "*" QCPAxisRect : uses
CCustomPlotExtended "1" *-- "*" QCPGraph : uses

@enduml