
@startuml

skinparam backgroundColor #FEFEFE
skinparam wrapWidth 600
package "DMA_Analyzer" #DDDDDD
{

class "CDLTRegexAnalyzerWorker"
{
}

class "CMTAnalyzer"
{
}

}

package "DMA_Analyzer_API" #DDDDDD
{

abstract class "IDLTMessageAnalyzerController"
{
    + {abstract} virtual int getMaximumNumberOfThreads() const = 0
    + signal void progressNotification( const tProgressNotificationData& progressNotificationData )
    + {abstract} virtual tRequestId requestAnalyze( const std::weak_ptr<IDLTMessageAnalyzerControllerConsumer>& pClient, const tRequestParameters& requestParameters ) = 0
    + {abstract} virtual void cancelRequest( const std::weak_ptr<IDLTMessageAnalyzerControllerConsumer>& pClient, const tRequestId& requestId ) = 0
}

abstract class "IDLTMessageAnalyzerControllerConsumer"
{
    + {abstract} virtual slot void progressNotification( const tProgressNotificationData& progressNotificationData ) = 0
    + tRequestId requestAnalyze( const tRequestParameters& requestParameters )
}

}

package "DMA_Common" #DDDDDD
{

class "CBGColorAnimation"
{
}

class "CRegexDirectoryMonitor"
{
}

class "CTableMemoryJumper"
{
}

}

package "DMA_CoverageNote" #DDDDDD
{

class "CCoverageNoteProvider"
{
}

class "CoverageNoteTableModel"
{
}

}

package "DMA_CoverageNote_API" #DDDDDD
{

class "CCoverageNoteComponent"
{
}

class "ICoverageNoteProvider"
{
}

}

package "DMA_FiltersView" #DDDDDD
{

class "CFilterItemDelegate"
{
}

}

package "DMA_FiltersView_API" #DDDDDD
{

class "CFiltersView"
{
}

class "IFiltersModel"
{
    + {abstract} virtual void addCompletionData( const tFoundMatches& foundMatches ) = 0
    + {abstract} virtual void filterRegexTokens( const QString& filter ) = 0
    + {abstract} virtual void resetCompletionData() = 0
    + {abstract} virtual void resetData() = 0
    + {abstract} virtual void setUsedRegex(const QString& regexStr) = 0
}

}

package "DMA_GroupedView" #DDDDDD
{

class "CGroupedViewModel"
{
}

}

package "DMA_GroupedView_API" #DDDDDD
{

class "CGroupedView"
{
}

}

package "DMA_Log" #DDDDDD
{

class "CConsoleCtrl"<< (S,#FF7700) Singleton >>
{
}

class "CConsoleInputProcessor"
{
}

}

package "DMA_Log_API" #DDDDDD
{

class "CConsoleView"
{
}

}

package "DMA_Logo_API" #DDDDDD
{

class "CLogo"
{
}

}

package "DMA_LogsWrapper_API" #DDDDDD
{

class "IFileWrapper"
{
    + {abstract} virtual QString getCacheStatusAsString() const = 0
    + {abstract} virtual QString getFileName(int num = 0) = 0
    + {abstract} virtual bool cacheMsgByIndex( const tMsgId& msgId ) = 0
    + {abstract} virtual bool cacheMsgByIndexes( const QSet<tMsgId> msgIdSet ) = 0
    + {abstract} virtual bool cacheMsgByRange( const tIntRange& msgRange ) = 0
    + {abstract} virtual bool cacheMsgWrapper( const int& msgId, const tMsgWrapperPtr& pMsgWrapper ) = 0
    + {abstract} virtual bool getSubFilesHandlingStatus() const = 0
    + {abstract} virtual bool isFiltered() const = 0
    + {abstract} virtual int getMsgIdFromIndexInMainTable(int msgIdxInMainTable) const = 0
    + {abstract} virtual int getNumberOfFiles() const = 0
    + {abstract} virtual int size() const = 0
    + {abstract} virtual int sizeNonFiltered() const = 0
    + signal void currentSizeMbChanged(tCacheSizeMB MBytes)
    + signal void fullChanged(bool isFull)
    + signal void isEnabledChanged(bool isEnabled)
    + signal void loadChanged(unsigned int percents)
    + signal void maxSizeMbChanged(tCacheSizeMB MBytes)
    + {abstract} virtual tIntRangeProperty normalizeSearchRange( const tIntRangeProperty& inputRange) = 0
    + {abstract} virtual tMsgWrapperPtr getMsg(const tMsgId& msgId) = 0
    + {abstract} virtual virtual tIntRangeList getSubFilesSizeRanges() const = 0
    + {abstract} virtual void copyFileNameToClipboard( const int& msgId ) const = 0
    + {abstract} virtual void copyFileNamesToClipboard( const tIntRange& msgsRange ) const = 0
    + {abstract} virtual void resetCache() = 0
    + {abstract} virtual void setEnableCache(bool isEnabled) = 0
    + {abstract} virtual void setMaxCacheSize(const tCacheSizeB& cacheSize ) = 0
    + {abstract} virtual void setMessageDecoder( IMsgDecoder* pMessageDecoder ) = 0
    + {abstract} virtual void setSubFilesHandlingStatus(const bool& val) = 0
}

}

package "DMA_PatternsView_API" #DDDDDD
{

class "CPatternsView"
{
}

class "CTreeRepresentationDelegate"
{
}

class "IPatternsModel"
{
    + {abstract} virtual QModelIndex addData(const QString& alias, const QString& regex, Qt::CheckState isCombine, Qt::CheckState isDefault) = 0
    + {abstract} virtual QModelIndex addData(const QString& alias, const QString& regex, Qt::CheckState isDefault = Qt::Unchecked) = 0
    + {abstract} virtual QModelIndex editData(const QModelIndex& idx, const QString& alias, const QString& regex, Qt::CheckState isDefault, Qt::CheckState isCombine) = 0
    + {abstract} virtual QString getAliasEditName( const QModelIndex& idx ) = 0
    + {abstract} virtual removeData(const QModelIndex& idx) = 0
    + {abstract} virtual signal void patternsRefreshed() = 0
    + {abstract} virtual tSearchResult search( const QString& alias ) = 0
    + {abstract} virtual void filterPatterns( const QString& filter ) = 0
    + {abstract} virtual void refreshRegexPatterns() = 0
    + {abstract} virtual void resetData() = 0
    + {abstract} virtual void updatePatternsInPersistency() = 0
    + {abstract} virtual void updateView() = 0
}

}

package "DMA_PlantumlView" #DDDDDD
{

class "CImageViewer"
{
}

}

package "DMA_PlantumlView_API" #DDDDDD
{

class "CUMLView"
{
}

}

package "DMA_PlotView_API" #DDDDDD
{

class "CPlotViewComponent"
{
}

}

package "DMA_Plugin" #DDDDDD
{

class "DLTMessageAnalyzerPlugin"
{
}

}

package "DMA_Plugin_API" #DDDDDD
{

class "Form"
{
}

}

package "DMA_RegexHistory" #DDDDDD
{

class "CExtendedCompleter"
{
}

class "CRegexHistoryProvider"
{
}

}

package "DMA_RegexHistory_API" #DDDDDD
{

class "CRegexHistoryTextEdit"
{
}

class "IRegexHistoryProvider"
{
}

}

package "DMA_SearchView" #DDDDDD
{

class "CSearchResultHighlightingDelegate"
{
}

class "CSearchResultModel"
{
}

}

package "DMA_SearchView_API" #DDDDDD
{

class "CSearchResultView"
{
}

class "CSearchViewComponent"
{
}

}

package "DMA_Settings_API" #DDDDDD
{

class "ISettingsManager"
{
}

}

package "Qt" #DDDDDD
{

abstract class "QAbstractItemModel"
{
}

abstract class "QAbstractTableModel"
{
}

class "QCompleter"
{
}

class "QElapsedTimer"
{
}

class "QFileSystemWatcher"
{
}

class "QImage"
{
}

class "QLineEdit"
{
}

class "QListView"
{
}

class "QObject"
{
}

class "QPlainTextEdit"
{
}

class "QProcess"
{
}

class "QPushButton"
{
}

class "QStyledItemDelegate"
{
}

class "QTabWidget"
{
}

class "QTableView"
{
}

class "QTextEdit"
{
}

class "QThread"
{
}

class "QTimer"
{
}

class "QTreeView"
{
}

class "QWidget"
{
}

}

package "qcustomplot" #DDDDDD
{

class "QCPAxisRect"
{
}

class "QCPGraph"
{
}

class "QCPLayerable"
{
}

class "QCPLegend"
{
}

class "QCustomPlot"
{
}

}

'====================Inheritance section====================
QObject <|-- CDLTRegexAnalyzerWorker : extends
QObject <|-- IDLTMessageAnalyzerController : extends
QObject <|-- IDLTMessageAnalyzerControllerConsumer : extends
QObject <|-- CBGColorAnimation : extends
QObject <|-- CRegexDirectoryMonitor : extends
QAbstractTableModel <|-- CoverageNoteTableModel : implements
QObject <|-- ICoverageNoteProvider : extends
QStyledItemDelegate <|-- CFilterItemDelegate : extends
QTreeView <|-- CFiltersView : implements
QAbstractItemModel <|-- IFiltersModel : implements
QAbstractItemModel <|-- CGroupedViewModel : implements
QTreeView <|-- CGroupedView : extends
QObject <|-- CConsoleCtrl : extends
QObject <|-- CConsoleInputProcessor : extends
QPlainTextEdit <|-- CConsoleView : extends
QPushButton <|-- CLogo : extends
QObject <|-- IFileWrapper : extends
QTreeView <|-- CPatternsView : extends
QStyledItemDelegate <|-- CTreeRepresentationDelegate : extends
QAbstractItemModel <|-- IPatternsModel : implements
QWidget <|-- CImageViewer : extends
QWidget <|-- CUMLView : extends
QObject <|-- DLTMessageAnalyzerPlugin : extends
QWidget <|-- Form : extends
QCompleter <|-- CExtendedCompleter : extends
QTextEdit <|-- CRegexHistoryTextEdit : extends
QObject <|-- IRegexHistoryProvider : extends
QStyledItemDelegate <|-- CSearchResultHighlightingDelegate : extends
QAbstractTableModel <|-- CSearchResultModel : implements
QTableView <|-- CSearchResultView : extends
QObject <|-- CSearchViewComponent : extends
QObject <|-- ISettingsManager : extends
QObject <|-- QCPAxisRect : extends
QObject <|-- QCPGraph : extends
QObject <|-- QCPLayerable : extends
QObject <|-- QCPLegend : extends
QWidget <|-- QCustomPlot : extends

'====================Dependencies section====================
CMTAnalyzer "1" *-- "*" QThread : contains
CBGColorAnimation "1" o-- "1" QWidget : animation widget
CRegexDirectoryMonitor "1" *-- "1" QFileSystemWatcher : contains
CTableMemoryJumper "1" o-- "1" QTableView : contains
CCoverageNoteProvider "1" o-- "1" QLineEdit : passes to nested entities
CCoverageNoteProvider "1" o-- "1" QPushButton : passes to nested entities
CCoverageNoteProvider "1" o-- "2" QTableView : passes to nested entities
CCoverageNoteProvider "1" o-- "4" QTextEdit : passes to nested entities
CCoverageNoteComponent "1" o-- "1" QLineEdit : passes to nested entities
CCoverageNoteComponent "1" o-- "1" QPushButton : passes to nested entities
CCoverageNoteComponent "1" o-- "2" QTableView : passes to nested entities
CCoverageNoteComponent "1" o-- "4" QTextEdit : passes to nested entities
CFilterItemDelegate "1" o-- "1" QCompleter : uses
CFilterItemDelegate "1" o-- "1" QTreeView : parent view
CConsoleCtrl "1" o-- "1" QPlainTextEdit : console text edit
CConsoleCtrl "1" o-- "1" QTabWidget : console view tab widget
CConsoleCtrl "1" o-- "1" QWidget : console tab
CConsoleInputProcessor "1" o-- "1" QLineEdit : console input
CPatternsView "1" o-- "1" QLineEdit : patterns search input
CImageViewer "1" *-- "1" QImage : contains
CUMLView "1" *-- "2" QProcess : contains
CPlotViewComponent "1" o-- "1" QPushButton : uses
DLTMessageAnalyzerPlugin "1" *-- "1" QTimer : contains
CRegexHistoryProvider "1" *-- "1" QListView : creates
CRegexHistoryTextEdit "1" o-- "1" QCompleter : uses
CSearchResultView "1" o-- "1" QTabWidget : uses main tab widget
CSearchResultView "1" o-- "1" QTableView : uses dlt-viewer main table view
CSearchViewComponent "1" o-- "1" QTabWidget : uses

@enduml