
@startuml

skinparam backgroundColor #FEFEFE
skinparam wrapWidth 600
package "Qt" #DDDDDD
{

abstract class "QAbstractItemModel"
{
}

abstract class "QAbstractTableModel"
{
}

class "QCompleter"
{
}

class "QElapsedTimer"
{
}

class "QFileSystemWatcher"
{
}

class "QImage"
{
}

class "QLineEdit"
{
}

class "QListView"
{
}

class "QObject"
{
}

class "QPlainTextEdit"
{
}

class "QProcess"
{
}

class "QPushButton"
{
}

class "QStyledItemDelegate"
{
}

class "QTabWidget"
{
}

class "QTableView"
{
}

class "QTextEdit"
{
}

class "QThread"
{
}

class "QTimer"
{
}

class "QTreeView"
{
}

class "QWidget"
{
}

}

@enduml