@startuml

'QT's classes
class QWidget
class QScrollArea
class QProcess

'Plugin's classes
class CImageViewer
{
    --public API--
    +CImageViewer(QWidget *parent = nullptr)
    +bool loadFile(const QString &)
    +void clear()
}

class CUMLView
{
    --public API--
    +CUMLView(QWidget *parent = nullptr)
    +void generateUMLDiagram(const QString& diagramContent)
    +bool isDiagramGenerationInProgress() const
    +void cancelDiagramGeneration()
    +void clearDiagram()
    +bool isDiagramShown() const
	--signals--
    +void diagramGenerationStarted()
    +void diagramGenerationFinished(bool success)
}

class Form

class CDLTMessageAnalyzer
{
}

class plantuml
{
}

'Inheritance section
QWidget <|-- CImageViewer : extends
QScrollArea <|-- CUMLView : extends

'Composition section
Form "1" *--- "1" CUMLView : contains
CUMLView "1" *--- "1" CImageViewer : contains
CUMLView "1" *--- "2" QProcess : contains
QProcess "1" *--- "1" plantuml : runs jar

'Agregation section
CDLTMessageAnalyzer "1" o--- "1" CUMLView : using

@enduml