@startuml

left to right direction

'QT's classes
package "Qt" #DDDDDD 
{
    class QWidget
    class QTableView
    class QTreeView
    class QAbstractItemModel
}

'Plugin's classes
package "DMA base" #DDDDDD 
{
    class Form
    class CDLTMessageAnalyzer{}
}

package "DMA patterns view" #DDDDDD 
{
    class CPatternsModel{}
    class CPatternsView {} 
    class CPatternsFileView{}
    class Ui_PatternsFileForm {}
}

package "DMA authentication" #DDDDDD 
{
    class CAuthenticationModel{}
    class CAuthenticationView {}
    class CAuthenticationItemView {}
    class Ui_AuthenticationItemForm {}
}

package "DMA network" #DDDDDD 
{
    interface INetworkCtrl{}
    class CNetworkCtrl{}
}

package "DMA settings"
{
    class CSettingsManager
    { 
        shouldMigrateUserSettingsToSQLiteDB() 
    }
}

'Inheritance section
QTreeView <|-- CPatternsView : extends
QAbstractItemModel <|-- CPatternsModel : implements
QTableView <|-- CAuthenticationView : extends
QAbstractItemModel <|-- CAuthenticationModel : implements
QWidget <|-- CAuthenticationItemView : extends
QWidget <|-- CPatternsFileView : extends
INetworkCtrl <|-- CNetworkCtrl : implements

'Composition section
CDLTMessageAnalyzer "1" *-- "1" CPatternsModel : creates and provides
Form "1" *-- "1" CPatternsView : creates and provides
CPatternsFileView "1" *-- "1" Ui_PatternsFileForm : contains
CAuthenticationItemView "1" *-- "1" Ui_AuthenticationItemForm : contains
CPatternsView "1" *-- "1" CPatternsFileView : contains
CDLTMessageAnalyzer "1" *-- "1" CAuthenticationModel : creates and provides
CDLTMessageAnalyzer "1" *-- "1" CAuthenticationView : creates and provides
CDLTMessageAnalyzer "1" *-- "1" INetworkCtrl : contains

'Agregation section
CDLTMessageAnalyzer "1" o-- "1" CPatternsView : gets and uses
CPatternsFileView "1" o-- "1" CAuthenticationView : gets and uses
CAuthenticationView "1" o-- "1" CAuthenticationModel : gets and uses
CPatternsView "1" o-- "1" CPatternsModel : gets and uses
CPatternsFileView "1" o-- "1" INetworkCtrl : gets and uses
CPatternsView "1" o-- "1" INetworkCtrl : gets and uses

@enduml